### ISSUE TITLE
Flow Element Crown

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1]
When you click on a flow element on the canvas two icons should appear to the right of the element. These icons are a flow segment and a trash can. 

Clicking on the flow element will allow for drawing a line from the current element to another.

Clicking on the trash can will remove that element.

<img width="275" alt="screenshot 2018-10-08 14 58 22" src="https://user-images.githubusercontent.com/535300/46635900-d183fe00-cb0a-11e8-819b-c78c88066852.png">

**Comment by tdondich** [comment]
There should be some level of configuration for crown, very much like how there is an inspector config for each element vue component. 

So ideally there's a crownConfig, which specifies element and method handler when the crown item is clicked.

**Comment by tdondich** [comment]
Actual implementation of at least the trash icon for the "crown" should be done in this ticket.  Adding ability to "connect" elements together through a BPM sequential flow can be in another ticket.
