### ISSUE TITLE
Message Flow Names Not Saving

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1011]
https://www.dropbox.com/s/cpayv2t3uslkpvh/message-name-not-saving.mp4?dl=0

**Comment by tuantruong625** [comment]
Fixed in the latest develop branch.
https://github.com/ProcessMaker/modeler/commit/b8a2df3cfd632ef5336929d06bba4a4d5bba85b9

**Comment by chipit24** [comment]
🔥 **_hot_** 🔥 **_fix_** 🔥 was pushed to `develop` that should resolve this: https://github.com/ProcessMaker/modeler/commit/b8a2df3cfd632ef5336929d06bba4a4d5bba85b9.
