### ISSUE TITLE
Boundary Catch Doesn't work

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1017]
![image](https://user-images.githubusercontent.com/535300/72280777-fad4e900-35ed-11ea-8916-d06fcdd632f7.png)

When you add a message catch event (in the boundary) there is no way to configure which to message you are catching. Also you cannot connect a message flow to a message boundary catch from an intermediate throw event.

Message Throw is missing the Message Flow

![image](https://user-images.githubusercontent.com/535300/72280668-b6e1e400-35ed-11ea-9a26-2c4bf90608ee.png)

Correct Message Catch Config

![image](https://user-images.githubusercontent.com/535300/72280846-2526a680-35ee-11ea-85e6-e77c27104773.png)

**Comment by velkymx** [comment]
The fix is to remove the ability to add a boundary message catch to ONLY sub processes

**Comment by lisa-fehr** [comment]
I believe this was addressed in https://github.com/ProcessMaker/modeler/issues/1021
