### ISSUE TITLE
Display usernames alongside full names when adding permissions

### ISSUE THREAD

**Issue by PMQABen** [ProcessMaker/modeler#1033]
## Description
When adding a user to permissions for an event or task, we always show the first and last name of the user. In the event of a company having two users with the same first and last name, you will not be able to tell which is which:
![image](https://user-images.githubusercontent.com/28575916/72560184-5fe14680-385b-11ea-98e6-e3f90651dace.png)

## Expected behavio(u)r
Display the username next to the user's fullname. Example screencap from the "add users to group" modal:
![image](https://user-images.githubusercontent.com/28575916/72561095-48a35880-385d-11ea-9a6a-e61f1ccfcee6.png)

**Comment by chipit24** [comment]
The Users dropdown is added to tasks using the `registerInspectorExtension` method in the `modeler-init` event callback. For example, see https://github.com/ProcessMaker/processmaker/blob/bf532c273372838946b47073eaf694791ac37f55/resources/js/processes/modeler/initialLoad.js#L136.

The actual component that displays the dropdown also exists in the `processmaker` repo: https://github.com/ProcessMaker/processmaker/blob/develop/resources/js/processes/modeler/components/inspector/TaskAssignment.vue.

So the changes required to add this feature will have to be done in that repo.
