### ISSUE TITLE
Closer Element Support

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1037]
Allow closer items threshold for sequence flows before they try to redraw/reroute themselves.

**Comment by chipit24** [comment]
This is the same issues as the one described in https://github.com/ProcessMaker/modeler/issues/759. Allowing sequence flows to flow in a reasonable manner and be close to elements will require writing our own router: https://resources.jointjs.com/docs/jointjs/v3.1/joint.html#routers.custom.

**Comment by chipit24** [comment]
On hold for clarification and prioritization.

**Comment by chipit24** [comment]
@velkymx Looks like this was much easier to accomplish than expected; I have a PR up with a screenshot showing what it looks like: https://github.com/ProcessMaker/modeler/pull/1047.

Do you have a link to a process where this was an issue before, so I can test it with that?
