### ISSUE TITLE
Connector Naming

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1038]
Connector tasks should be re-namable, just like tasks

**Comment by sanjacornelius** [comment]
- [ ] Connector Send Email
- [ ] Connector PDF
- [ ] Connector Sales Force
- [ ] Connector Slack

**Comment by sanjacornelius** [comment]
I believe that is all the connectors/packages that needed to be updated if there are any more list them here. 

All open PR's that need review are linked.
