### ISSUE TITLE
Message Start Event Crash

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1044]
When you drag a new start event on to the canvas and choose the Message Start, the whole browser freezes up.

![image](https://user-images.githubusercontent.com/535300/72854247-a3c3b980-3c68-11ea-9f94-25e618b61480.png)

**Comment by velkymx** [comment]
Also freezes if you try to change to that type.

**Comment by johnblackspear** [comment]
## Steps to reproduce, using Chrome

### For https://develop.spark.qa.processmaker.net/modeler/1

Set timezone to PST:
<img src="https://user-images.githubusercontent.com/28595383/72922839-b233d300-3d45-11ea-99dc-2ac405693f12.png" width="350" />

Set time to after 16h:
<img src="https://user-images.githubusercontent.com/28595383/72922895-ced00b00-3d45-11ea-8108-0718f31874e0.png" width="350" />

Drag a start element on to the page, and choose "Start Timer Event".

### For standalone (localhost:8080)

Timezone does not seem to be important, set the time to any time that is the next day in UTC.

Drag a start element on to the page, and choose "Start Time Event".
