### ISSUE TITLE
Crown Shifts After Change Type

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1049]
Before:

![image](https://user-images.githubusercontent.com/535300/72932125-00c87980-3d14-11ea-9976-98fd2b42e975.png)

After:

![image](https://user-images.githubusercontent.com/535300/72932102-f3ab8a80-3d13-11ea-85a4-96cf42d4138b.png)

Fix: Crown should not move from the initial position.

**Comment by lisa-fehr** [comment]
@velkymx The crown seems to be in the same spot, it just has one less item in it. Should flow icons show up but be disabled to keep it the same width?

**Comment by velkymx** [comment]
This is fine. The flow is missing in the second one.
