### ISSUE TITLE
Add Signal End Event

### ISSUE THREAD

**Issue by chipit24** [ProcessMaker/modeler#1062]
<img width="78" alt="Screen Shot 2020-01-27 at 2 57 56 PM" src="https://user-images.githubusercontent.com/7561061/73209021-6e5e1680-4115-11ea-8263-43913a4b81c2.png">

Acceptance criteria:
 * The signal end event should have a solid border with a triangle like in the screenshot above.
   * The event should have a red stroke colour like the other end events.
 * The signal end event should be accessible from the "cog" dropdown under the base end event.
 * It should produce the following BPMN XML:
   ```xml
   <endEvent id="signal">
     <signalEventDefinition />
   </endEvent>
   ```

**Comment by johnblackspear** [comment]
Red colour as per the other elements is #ED4757
