### ISSUE TITLE
Add Signal Intermediate Throwing Event

### ISSUE THREAD

**Issue by tuantruong625** [ProcessMaker/modeler#1064]
<img width="44" alt="Screen Shot 2020-01-27 at 4 28 15 PM" src="https://user-images.githubusercontent.com/26545455/73215382-0661fd00-4122-11ea-9335-2889c3abaf0f.png">

Acceptance criteria:
The element icon should be yellow with a solid fill.
The signal Intermediate catch event should be accessible from the "cog" dropdown under the base start event.

Valid XML
```
<intermediateThrowEvent id="signal">
  <signalEventDefinition signalRef="newCustomerSignal" />
</intermediateThrowEvent>
```

Inspector
<img width="257" alt="Screen Shot 2020-01-27 at 4 33 59 PM" src="https://user-images.githubusercontent.com/26545455/73215838-d36c3900-4122-11ea-849f-0d2d27706603.png">
- Set Name
- Set Signal for signanl intermediate catch events to listen for
 * And a Node Identifier input under Advanced:
   <img width="255" alt="Screen Shot 2020-01-27 at 2 52 08 PM" src="https://user-images.githubusercontent.com/7561061/73208587-b7619b00-4114-11ea-83e5-1f7ce8a833d7.png">
 * If the signal referenced by this element's `signalRef` is removed, the reference on this element should be removed as well.

**Comment by lisa-fehr** [comment]
> If the signal referenced by this element's signalRef is removed, the reference on this element should be removed as well.

Might be better in its own ticket: https://github.com/ProcessMaker/modeler/issues/1060
