### ISSUE TITLE
Add removeSignalRef after Listen for Signal dropdown is implemented

### ISSUE THREAD

**Issue by lisa-fehr** [ProcessMaker/modeler#1075]
When Listen for Signal dropdown is implemented, add code to remove the signalRef when signal is deleted.

IE: Signal End Event
```
destroyed() {
    store.commit('removeSignalRef', this.signal);
  },
```

Add tests for removing signal on Signal Start and Intermediate Signal Catch at minimum. Similar to test: "Removes messageRef when message is deleted"

**Comment by chipit24** [comment]
Issue fixed in merged PR, closing.
