### ISSUE TITLE
Boundary events moves around when dragging pool

### ISSUE THREAD

**Issue by chipit24** [ProcessMaker/modeler#1093]
## Description
When you drag a pool that contains a boundary event, the boundary event moves around but it should stay attached to the task.

## Reproduction steps
1. Drag a task onto the grid.
2. Add a boundary event onto the task.
3. Drag a pool onto the grid.
4. Drag the pool around. 

## Expected behaviour
The boundary event should stay attached to the pool and not move in relation to the task it is attached to.

## Actual behaviour
The boundary event flies around:
![boundary-event-pool-bug](https://user-images.githubusercontent.com/7561061/73972475-e6cf8f00-48ee-11ea-93d4-75b931c761b8.gif)

## Software used
Latest modeler develop branch running on Chrome 79 on macOS Catalina.

**Comment by lisa-fehr** [comment]
Similar Issue: https://github.com/ProcessMaker/modeler/issues/731

**Comment by lisa-fehr** [comment]
Seems to behave as expected in v. 0.17.9
