### ISSUE TITLE
Service Tasks Different Size

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1096]
The service task element is just a little different than other tasks. It's causing issues with lines. 

![image](https://user-images.githubusercontent.com/535300/74051857-9fe4a680-498d-11ea-9ffe-753daca8c05b.png)

Please make the same size.

**Comment by chipit24** [comment]
Looks like the sequence flow alignment issue happens even when a regular task is enlarged by giving it a long name:
<img width="452" alt="Screen Shot 2020-02-07 at 1 50 57 PM" src="https://user-images.githubusercontent.com/7561061/74056976-f7483e00-49b0-11ea-9c56-40a55af9ee03.png">

Looks like the size of the connector-send-email task is set to 76 x 116: 
https://github.com/ProcessMaker/connector-send-email/blob/1b84b27f36a49e5d527484bdf8fb5a9bfc1e22fa/resources/js/connectors/email/send/index.js#L34-L35

This is the same dimensions as every other task in modeler: https://github.com/ProcessMaker/modeler/blob/81ab6700ae8ae9baa5f137380d8f7f0996e13610/src/components/nodes/task/taskConfig.js#L1-L2

Even the additional of a single line seems to increase the height of the task just slightly, causing a small kink in the sequence flow:
<img width="886" alt="Screen Shot 2020-02-07 at 1 58 50 PM" src="https://user-images.githubusercontent.com/7561061/74057490-0c719c80-49b2-11ea-8520-485ac5e914e7.png">

So this is not an issue with Service Tasks, but an issue with all tasks in general.

**Comment by chipit24** [comment]
I think the best solution for this would be:
 * Don't increase the size of the component unless the label is at least 3 lines long.
 * When increasing the size of the task, do it by a factor of the paper grid size to prevent the flow from having to bend to move to the centre of the shape.

**Comment by lisa-fehr** [comment]
Noticing that the height of the node is changed even if the label isn't overflowing.

Task.vue
![Screen Shot 2020-02-07 at 4 08 44 PM](https://user-images.githubusercontent.com/6653340/74066016-38961900-49c4-11ea-9389-f2fe17908997.png)

My `height` was bigger than the `labelHeight + labelPadding + topAndBottomMarkersSpace` for a Basic Task.

**Comment by chipit24** [comment]
Another think to address as part of this, is ensuring the height is reset after clearing the name:
![task_not_resizing_after_clearning_name](https://user-images.githubusercontent.com/7561061/74178111-01fd1000-4c09-11ea-9893-c4778ab4ae8d.gif)
