### ISSUE TITLE
Align and distribute shapes

### ISSUE THREAD

**Issue by johnblackspear** [ProcessMaker/modeler#1098]
# Enhancement: Align and distribute
## Description
We should be able to align and distribute shapes that are (multi-)selected on the page.

## Align
We should be able to
 - align to the left (all items line up with the minimum x value of the group of selected items)
 - align to the right
 - align to the top
 - align to the bottom
 - align centers along the vertical axis
 - align centers along the horizontal axis

## Distribute
Elements will be distributed by making sure the space between their centres is the same (distribute centre). This is how distribute is implemented in Camunda.

## Proposed alignment options:
![image](https://user-images.githubusercontent.com/28595383/74067135-6ee98d80-49f0-11ea-9048-230ad9fce798.png)

## Proposed distribution options:
![image](https://user-images.githubusercontent.com/28595383/74067163-7f016d00-49f0-11ea-950d-ae84fc0d12c6.png)

## Acceptance criteria
 * Create an icon for each of the alignment and distribution actions above (8 icon buttons in total).
    * These icons should be placed in the toolbar with the other buttons.
    * The buttons should be disabled until at least 2 shape are selected.
    * Remove the shortcut keys that currently map to these actions; use only the buttons.
 * Clicking the toolbar buttons should align / distribute the selected shapes as outlines in the sections above.
 * This feature shouldn't affect boundary events, flows (sequence flows, message flows, association flows), or lanes.
 * With pools:
    * If pools are included in the selection, apply align / distribute only to the pools, not the elements inside the pools.
    * If there are pool elements included in the selection, apply align / distribute relative to the elements inside each pool, not globally for all elements in every pool.

**Comment by johnblackspear** [comment]
Some current issues with the WIP:

 - [ ] shapes without a `size()` breaks the bounding box logic

**Comment by chipit24** [comment]
This is now complete! 🎊🇨🇦👨‍💻👩‍💻
