### ISSUE TITLE
Add eslint and stylelint, fix lint errors

### ISSUE THREAD

**Issue by chipit24** [ProcessMaker/modeler#11]
Add eslint and stylelint configurations to the project root, and lint the entire codebase based on these configurations.

**Comment by tdondich** [comment]
Weird, the vue-cli should already have eslint built in as it was complaining in my editor.  Package.json shows eslint included with recommended rules.

**Comment by chipit24** [comment]
@tdondich you're right. The ESLint config is in `package.json`, and it seems my editor didn't pick up the config from there. I'm going to close this issue, as we're going to lint as we go anyway.
