### ISSUE TITLE
Message Flow are not available for some elements

### ISSUE THREAD

**Issue by caleeli** [ProcessMaker/modeler#1105]
# Message Flow are not available for some elements
## Description
Currently there are elements that could contain message elements but can not be connected using the message flows.

## Reproduction steps
Insert two pools, one pool with and End Message Event, the other one with and Start Message Event.

Try to draw a message flow between those elements.

End Message Flow Event --> Start Message Event

## Expected behavior
Any throw element (ex. Intermediate throw and End Event) with a Message Event Definition, must have a Message Flow button in its crown.

Any catch element (ex. Intermediate catch, boundary and Start Events) with a Message Event Definition, can be a valid target for a message flow.

![image](https://user-images.githubusercontent.com/8028650/74337392-95a01f00-4d76-11ea-92da-d53bb7d84471.png)

## Actual behavior
Not all the elements like End with message have the Message Flow

![image](https://user-images.githubusercontent.com/8028650/74337486-bec0af80-4d76-11ea-9e2d-879d9b71a5f3.png)

**Comment by chipit24** [comment]
The relevant bits from the spec regarding start and end events:

> <img width="670" alt="Screen Shot 2020-02-13 at 11 06 45 AM" src="https://user-images.githubusercontent.com/7561061/74457725-aa53e400-4e56-11ea-84d1-7bea6d8eaba4.png">
> <img width="667" alt="Screen Shot 2020-02-13 at 11 06 08 AM" src="https://user-images.githubusercontent.com/7561061/74457730-aaec7a80-4e56-11ea-8f09-0c1a13d1b3b4.png">
> 

So it seems start events can never be the source of a message flow, and end events can never be the target of message flows. Message flows can go from end events to start events.

Here is the message flow connection table:
> <img width="658" alt="Screen Shot 2020-02-13 at 11 49 44 AM" src="https://user-images.githubusercontent.com/7561061/74457944-f43cca00-4e56-11ea-894f-bad8f1213f90.png">
