### ISSUE TITLE
Can not attach intermediate events as boundary

### ISSUE THREAD

**Issue by caleeli** [ProcessMaker/modeler#1106]
# Can not attach intermediate events as boundary
## Description
In the current develop version, I can not attach intermediate events as boundary

## Reproduction steps
- Add a Task (normal user task)
- Drag an intermediate (timer or message) and try to attach it to the task

## Expected behavior
The user should be able to attach boundary events to the tasks

## Actual behavior
Can not attach intermediate events as boundary

![image](https://user-images.githubusercontent.com/8028650/74338147-fed46200-4d77-11ea-9ecc-f36783fc9fd6.png)
![image](https://user-images.githubusercontent.com/8028650/74338190-16134f80-4d78-11ea-93d9-144d9c98f23c.png)

## Other information
Current develop commit: f4f26bc1905e5cde2470c47811b22e44f5544304

**Comment by lisa-fehr** [comment]
Seems like once you drag an Intermediate Event onto a Task, the Intermediate Event is converted to a Boundary Event.

You can currently add a Boundary Timer Event, Boundary Error Event, and a Boundary Message event (currently, Boundary Message is only on a subprocess).

![Screen Shot 2020-02-13 at 11 43 39 AM](https://user-images.githubusercontent.com/6653340/74457328-1b46cc00-4e56-11ea-951a-b5e34aae9635.png)

![Screen Shot 2020-02-13 at 11 48 02 AM](https://user-images.githubusercontent.com/6653340/74457764-b8096980-4e56-11ea-8956-6be4fbe24a63.png)

Converting Intermediate Event to Boundary Events on drag would be a new feature.

**Comment by johnblackspear** [comment]
Hi David

We've been using a new process internally and for our classification and prioritization purposes I've changed the label from bug to enhancement.

Shout if you have questions on how we classify these :)

**Comment by velkymx** [comment]
Boundary events are attached via the task crown not the control toolbar
