### ISSUE TITLE
Missing day of week parameter to configure the Intermediate Timer Event 

### ISSUE THREAD

**Issue by caleeli** [ProcessMaker/modeler#1107]
# Missing day of week parameter to configure the Intermediate Timer Event  
## Description
The Cyclic Intermediate Timer Event has missing parameters

## Reproduction steps
Add a Intermediate Timer Event
- Go to the Timing control properties
- Select Type=Cycle
- Select week

## Expected behavior
It must have a property to select the week day
![image](https://user-images.githubusercontent.com/8028650/74339295-30e6c380-4d7a-11ea-9190-c683451b1067.png)

## Actual behavior
Missing week day selection in weekly cycles
![image](https://user-images.githubusercontent.com/8028650/74339375-55db3680-4d7a-11ea-82b3-e8ac67334536.png)

**Comment by lisa-fehr** [comment]
@caleeli `Start Timer` takes a Start Date. Should `Intermediate Timer Event` also have that field? Otherwise it starts 'today'.

![Screen Shot 2020-02-19 at 1 56 42 PM](https://user-images.githubusercontent.com/6653340/74865793-b68ce500-531f-11ea-84dc-19f95b18bffc.png)
