### ISSUE TITLE
Canvas Edit Labels

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1118]
As a process designer, I'd like to be able double click an element and edit the label on the canvas.

**Comment by chipit24** [comment]
@velkymx

Editing text elements directly isn't natively supported in SVG, neither is an input element. The two solutions are to overlay an HTML textarea, or to highlight the name input (or a hidden input that mirrors the name).

Overlay:
![edit-label-double-click](https://user-images.githubusercontent.com/7561061/74782670-e1206480-5271-11ea-958a-018bad737e01.gif)

Focus input:
![edit-label-focus](https://user-images.githubusercontent.com/7561061/74782681-e7164580-5271-11ea-9f2c-b3d1beaa17a0.gif)

The textarea overlay is cool, but is complicated and requires constantly re-computing a handful of properties to ensure it stays positioned and sized correctly. Scaling the paper would further complicate things. Going down this route would require a few days to implement this feature.

Simply focusing the name input by double click achieves a very similar user experience and could be implemented within a day.

**Comment by velkymx** [comment]
We think the focus on double click is fine. Let's move forward with that.
