### ISSUE TITLE
Export as PDF

### ISSUE THREAD

**Issue by chipit24** [ProcessMaker/modeler#1119]
Add a button to the right side of the validation bar allow exporting the current diagram as PDF.

**Comment by chipit24** [comment]
Waiting for clarification on requirements (example of how the PDF should work, and how it should allow or display comments).

**Comment by chipit24** [comment]
We will go ahead with a basic implementation and can add functionality for comments later.

Acceptance criteria:
 * A "Export PDF" button, with a font-awesome "download" icon should be in the "validation" footer, aligned to the left side.
 * The PDF should contain an image of the current process, as is. The background grid and highlighting do not need to be included in the export.

**Comment by johnblackspear** [comment]
Closing this as after discussion we went for a printable view with documentation in core, addressed in https://github.com/ProcessMaker/processmaker/pull/2996.
