### ISSUE TITLE
Add Download BPMN button

### ISSUE THREAD

**Issue by chipit24** [ProcessMaker/modeler#1120]
Add a button to the validation footer to allow downloading the current process as a BPMN file.

Acceptance criteria:
 * Move the current "Download XML" button from the title bar to the left side of the validation bar footer.
 * The button should display "Download BPMN", and should prompt the user to save the current process an a `.bpmn` file.

**Comment by chipit24** [comment]
Todo: Add missing download functionality to `ModelerApp.vue` in PM core app.

**Comment by johnblackspear** [comment]
Thanks for taking this, Rob. AFAIK this is now done - please check Ryan's PR on Friday (https://github.com/ProcessMaker/processmaker/pull/2938)
