### ISSUE TITLE
highlight errors with connector-send-email when current modeler is linked in core

### ISSUE THREAD

**Issue by lisa-fehr** [ProcessMaker/modeler#1133]
# Bug report issue
## Description
There are console errors in core when dragging a task onto the grid. Happens when the connector-send-email package is installed. This could affect other packages. 
## Reproduction steps
- Add this to your composer.json in processmaker::
```
"repositories": [
    ...
    {
      "type": "vcs",
      "url": "/localpath-to-connector-send-email"
    }
```
- Then follow the instructions for installing the package. Can use default values.
https://github.com/ProcessMaker/connector-send-email

  (run composer require locally)
  (run artisan install on vagrant ssh)

- Link the current modeler into processmaker
- Add a task to the diagram
## Expected behaviour
There should be no console errors when dragging a task onto the diagram when this package is installed.
## Actual behaviour
Dragging a task onto the diagram causes multiple error messages that seem to be related to the highlighted element.
## Software used
Current modeler linked into core. Occurred after modeler v0.18.4 and is in the unreleased code.
## Other information
<img width="1274" alt="Screen Shot 2020-02-24 at 10 53 08 AM" src="https://user-images.githubusercontent.com/6653340/75173523-04796280-56fd-11ea-94b0-6662c40febbd.png">

**Comment by chipit24** [comment]
The issue seems to stem from the fact that `highlightedNode` no longer exists in `Modeler.vue`, but it accessed from the connector's helper method at:
https://github.com/ProcessMaker/connector-send-email/blob/86d32300f518ef6af552a60ad617d5b0f88af608/resources/js/helper.js#L7

**Comment by lisa-fehr** [comment]
Resolved in https://github.com/ProcessMaker/modeler/pull/1141
