### ISSUE TITLE
Task Marker: Multiple Instance

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1134]
Add support for rendering of *Multiple Instance* task markers in task elements.

A multi-instance activity is a way of defining repetition for a certain step in a business process. In programming concepts, a multi-instance matches the for each construct: it allows execution of a certain step or even a complete subprocess for each item in a given collection, sequentially or in parallel.

A multi-instance is a regular activity that has extra properties defined (so-called multi-instance characteristics) which will cause the activity to be executed multiple times at runtime. Following activities can become multi-instance activities:

Service Task
Send Task
User Task
Business Rule Task
Script Task
Receive Task
Manual Task
(Embedded) Sub-Process
Call Activity
Transaction Subprocess

A Gateway or Event can not become multi-instance.

If an activity is multi-instance, this is indicated by three short lines at the bottom of the activity. Three vertical lines indicate that the instances will be executed in parallel, while three horizontal lines indicate sequential execution.

![image](https://user-images.githubusercontent.com/535300/76010380-a3ede080-5ec7-11ea-8452-715df66531a9.png)

**Comment by chipit24** [comment]
It looks like a multi-instance task that is executed sequentially will have the following BPMN:
```XML
<bpmn:task id="node_1">
  <bpmn:multiInstanceLoopCharacteristics isSequential="true" />
</bpmn:task>
```

And a multi-instance task that is executed in parallel will have the following BPMN:
```XML
<bpmn:task id="node_1">
  <bpmn:multiInstanceLoopCharacteristics />
</bpmn:task>
```

In Camunda, this is toggled using buttons in the element's crown:
<img width="323" alt="Screen Shot 2020-03-09 at 1 53 10 PM" src="https://user-images.githubusercontent.com/7561061/76242984-f0118b80-620d-11ea-91dc-5fc1e1d1b76f.png">

@velkymx How would you want this toggled in modeler?

Regarding the list of elements you provided: We've renamed Call Activity to Sub Process, but you list three of these elements:
 * (Embedded) Sub-Process
 * Call Activity
 * Transaction Subprocess

Modeler currently only has a Sub Process task. Is it sufficient to add this feature to only that "sub-process" type.

We don't have access to a lot of the task types you listed (I'm assuming they are added as connectors), but it looks like that list may include every single task type, in which case we can add this feature to the base task component which is extended by all the other task types.

**Comment by chipit24** [comment]
From standup:
 * Don't implement UI toggle yet; only add the ability to correctly render the marker if the appropriate BPMN attributes exist.
 * The marker could exist on all task types: add this feature to the base task element so it is inherited by all task elements.
