### ISSUE TITLE
Change Task to Form Task

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1135]
Change the name of the task in the crown from Task to Form Task.

**Comment by chipit24** [comment]
@velkymx Please clarify what you need done for this issue.

**Comment by chipit24** [comment]
Change the name of the element in the controls list from "Task" to "Form Task", and also change the element's default name to "Form Task":

<img width="392" alt="Screen Shot 2020-03-10 at 11 48 47 AM" src="https://user-images.githubusercontent.com/7561061/76331221-383fb500-62c5-11ea-93b9-e235bc7dd252.png">
