### ISSUE TITLE
Show Inspector on Focus

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1139]
When the menus are hidden and I click on an element I'd like the inspector to slide out so I can use it. Then when I click off of the element (on the canvas) the menu should slide away.

**Comment by chipit24** [comment]
Some additional use cases:
 * When multiple elements are selected, the inspector panel should slide open and remain open for the initially selected element.
 * When focus shifts from one element to another, keep the inspector panel open for the newly selected element.
 * The inspector panel should only slide closed when all elements are deselected (i.e. the background process is "highlighted").
