### ISSUE TITLE
Undo not working for changing pool position

### ISSUE THREAD

**Issue by chipit24** [ProcessMaker/modeler#114]
To reproduce:
 * Drag a pool onto the grid; ensure there is at least one item in the pool.
 * Drag the pool.
 * Undo the action. The item in the pool moves when the pool and all its children should move.

**Comment by caleeli** [comment]
![undo redo action moves an element outside the pool](https://user-images.githubusercontent.com/8028650/50654785-5c3a9480-0f64-11e9-8911-7d81c8d7b500.gif)
