### ISSUE TITLE
Colorize Elements

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1146]
![image](https://user-images.githubusercontent.com/535300/77086510-1cbc6480-69bf-11ea-8bc3-22e395a34335.png)

The color in the bubble is the BORDER / ICON color. The interior color should be 20-30% lighter (maybe more).

Example:

![image](https://user-images.githubusercontent.com/535300/77088946-65c1e800-69c2-11ea-81a8-4b7ffebba578.png)

Clicking on the rainbow icon will show the color picker (there is already one in the core product)

![image](https://user-images.githubusercontent.com/535300/77086744-686f0e00-69bf-11ea-84da-c569f52c298d.png)

Color information should be store as a custom PM4 attribute for the element

Colors that are defined in other elements in the current diagram will show in the recents palets here: 

![image](https://user-images.githubusercontent.com/535300/77088997-7a05e500-69c2-11ea-8ee3-9528d9bbad3c.png)

**Comment by breale** [comment]
awesome!

**Comment by velkymx** [comment]
The "WHITE" circle is to clear / go back to the default color.

**Comment by chipit24** [comment]
I've broken out changing the icon colour and adding the colour picker into separate issues:
 * https://github.com/ProcessMaker/modeler/issues/1154
 * https://github.com/ProcessMaker/modeler/issues/1155

**Comment by velkymx** [comment]
![image](https://user-images.githubusercontent.com/535300/77681886-46433600-6f53-11ea-979e-8585a9fc2b11.png)
