### ISSUE TITLE
Changing Task Types

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1149]
If you change the task type (for example from a script task to a manual task), not only do the sequence flows get incorrectly removed, the label of the task is also reset - the label should not be reset.

**Comment by chipit24** [comment]
Closing. This problem has been broken up and addressed in the following issues:
 * https://github.com/ProcessMaker/modeler/issues/1153
 * https://github.com/ProcessMaker/modeler/issues/1152
 * https://github.com/ProcessMaker/modeler/issues/1151
 * https://github.com/ProcessMaker/modeler/issues/1150
