### ISSUE TITLE
End Signal Event should not have a sequence flow crown option

### ISSUE THREAD

**Issue by lisa-fehr** [ProcessMaker/modeler#1162]
<img width="144" alt="Screen Shot 2020-03-26 at 2 51 18 PM" src="https://user-images.githubusercontent.com/6653340/77685432-d42e1980-6f71-11ea-9c38-c992eb1f663e.png">
<img width="267" alt="Screen Shot 2020-03-26 at 2 54 07 PM" src="https://user-images.githubusercontent.com/6653340/77685435-d42e1980-6f71-11ea-9d8d-b832afc2dcda.png">

**Comment by chipit24** [comment]
According to the spec, no end event should be allowed to have a sequence flow coming from it:
<img width="794" alt="Screen Shot 2020-04-02 at 3 28 44 PM" src="https://user-images.githubusercontent.com/7561061/78293548-b4a96a80-74f6-11ea-994c-6cd63d53a4b2.png">
<img width="732" alt="Screen Shot 2020-04-02 at 3 28 21 PM" src="https://user-images.githubusercontent.com/7561061/78293553-b7a45b00-74f6-11ea-9060-a6ce923ba85c.png">
