### ISSUE TITLE
Intermediate Timer Event & Boundary Timer Event Cycle sometimes missing weekdays

### ISSUE THREAD

**Issue by lisa-fehr** [ProcessMaker/modeler#1190]
# Bug report issue
## Description
Sometimes, when Cycle and Week are selected, the Weekday select is missing.
## Reproduction steps
- Add an Intermediate Timer Event or a Boundary Timer Event on a task
- Under Timing Controls, select Cycle
- Select Week
- Select Day
- Select Week
- (may need to select and reselect Week if that doesn't work)
## Expected behaviour
Weekday selection should show up when Week is selected
## Actual behaviour
Weekday selection disappears
## Software used
Latest modeler
## Other information
Should look like this:
![Screen Shot 2020-04-14 at 3 50 40 PM](https://user-images.githubusercontent.com/6653340/79269168-01336500-7e6a-11ea-9281-b5b12bc269a7.png)
Looks like this:
![Screen Shot 2020-04-14 at 4 07 23 PM](https://user-images.githubusercontent.com/6653340/79269225-18725280-7e6a-11ea-90a3-bb373af1d6d0.png)

**Comment by velkymx** [comment]
I was just talking with the training team about this. This is a blocker issue.
