### ISSUE TITLE
Message End Event - Missing Message Flows

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1192]
When you configure message events, to model the send "messages" to each other, they need to be connected by message flows. Need to add the ability to add a message flow from the message end to a message catch.

**Comment by chipit24** [comment]
@velkymx It seems this is possible on the latest modeler develop branch:
<img width="529" alt="Screen Shot 2020-04-16 at 11 08 35 AM" src="https://user-images.githubusercontent.com/7561061/79473105-ac5f2e00-7fd2-11ea-8320-c9bcbb53c428.png">

The BPMN spec states that "Message Flows _cannot connect to objects that are within the same Pool_". So trying to create that message flow outside of a pool, where it would be invalid, is disallowed:

<img width="262" alt="Screen Shot 2020-04-16 at 11 11 27 AM" src="https://user-images.githubusercontent.com/7561061/79473497-33140b00-7fd3-11ea-9fad-7b6011b13e7f.png">

**Comment by chipit24** [comment]
Closing as behaviour is working as expected.
