### ISSUE TITLE
Populate signal selector when adding a new signal

### ISSUE THREAD

**Issue by johnblackspear** [ProcessMaker/modeler#1194]
# Populate the Signal Selector when adding a new signal
## Description
Adding a signal while configuring a signal event does not populate an empty signal selector. It could be expected to populate it if it is empty.

If the Signal Selector does have a selected item then adding a new signal should NOT change it.

## Reproduction steps
Add a Signal Event (say, Signal Start Event).

Click on Signal.

Click on `...`

Add a new Signal.

The Signal Selector dropdown, even though currently empty, still has to manually select the newly-added signal.

![new_signal_does_not_populate](https://user-images.githubusercontent.com/28595383/79380255-b4c25500-7f4f-11ea-96da-ff5b35451533.gif)

**Comment by velkymx** [comment]
When a new signal is added, the signal select should refresh and reset to include the new signal.
