### ISSUE TITLE
Add ability to connect elements via a sequential flow

### ISSUE THREAD

**Issue by tdondich** [ProcessMaker/modeler#12]
Utilizing the crown and clicking, the ability to connect elements via sequential flow needs to be added. Ideally, this is done by clicking the flow icon in a crown on the source object, and then clicking on the target item.

Please refer to the camunda modeler for example of this.

For now, support start event to task, and task to task, and exclusive gateway to task, and task, and those elements to end/stop event.

These should be represented by Sequential Flow.

**Comment by enriquecolosa** [comment]
**Sequence Flow Restrictions**
- Pool & Lanes cannot be source or target for any kind of sequence flows
- Text Annotations cannot be source or target for any kind of sequence flows
- Empty End Events & Message End Events cannot be used to create a sequence flow to any element
- Start Event can create a sequence flow to any elements but start events or text annotations
- Start Events cannot be a target element on any circumstances 

*Note* For association flow please refer to #13.
