### ISSUE TITLE
Estimate: Web Entry package component

### ISSUE THREAD

**Issue by chipit24** [ProcessMaker/modeler#1209]
Todo:

Part 1:
 * Remove registerInspectorExtension(startEvent, config); from https://github.com/ProcessMaker/package-webentry/blob/master/resources/assets/js/register-inspector.js.
 * In the pacakge, create a config ("index.js" file) for the web entry start event, and a new Vue component ("webEntryStartEvent.vue"), and register it with the registerNode callback in the modeler-init event.
    * Ensure the elemetn is hidden by setting "control: false" in its config.
    * Give it a default webentry config so it can be identified during parsing.
    * When registering the node with the registerNode method, specify a custom parser that checks for a webentry key in the config.

Part 2:
 * Add ability to add additional items to the start event "cog dropdown".
 * Could be added to a structure similar to `this.nodeRegistry` in `Modeler.vue`, and passed down to the components.

**Comment by velkymx** [comment]
If the web entry is installed and then enabled we'd like to change the start event to:

![image](https://user-images.githubusercontent.com/535300/80390912-ef869000-8861-11ea-9b30-6671d31098dd.png)
