### ISSUE TITLE
Switching between selected script tasks does not refresh

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1220]
In process modeler, when you click from one script task to another, whatever is present in the config json editor box, in the inspector for the first selection, will remain present in the second one. this will cause serious confusions when editing multiple script tasks, and who knows if changing something in task 2 will actually save that json config in task 2.

**Comment by chipit24** [comment]
This has been fixed in https://github.com/ProcessMaker/modeler/pull/1218.
