### ISSUE TITLE
Reset Color Icon

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1221]
I'd like to change the color reset (the white circle) to use the redo icon instead.

https://fontawesome.com/icons/redo-alt?style=solid

**Comment by johnblackspear** [comment]
Hi @velkymx, here are a some styling options:

### 1. Similar to the current style:

![image](https://user-images.githubusercontent.com/28595383/80747678-54b4dc80-8b13-11ea-9d0f-1b72952557f8.png)

### 2. Bordered, background same as crown:

![image](https://user-images.githubusercontent.com/28595383/80747791-7a41e600-8b13-11ea-9c98-f4a12233f3ed.png)

### 3. No border:

![image](https://user-images.githubusercontent.com/28595383/80747866-99d90e80-8b13-11ea-8b2e-019f284ec5c8.png)

### 4. Something else?

**Comment by johnblackspear** [comment]
For posterity: Option 1 was chosen on Slack chat
