### ISSUE TITLE
Data Objects

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1246]
Model the data objects

**Comment by vehikl-jacare** [comment]
To implement this we need to create a new node that renders the following shape:
![Screen Shot 2020-11-09 at 3 24 16 PM](https://user-images.githubusercontent.com/68430564/98592372-a34fea00-229f-11eb-923c-45cb3e81a5ea.png)

 
And generates the following bpmn:

```xml 
<bpmn:dataObjectReference id="DataObjectReference_08wvnk2" name="DataObject1" />
```
