### ISSUE TITLE
Data Stores

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1247]

**Comment by vehikl-jacare** [comment]
To implement this we need to create a new node that renders the following shape:
![Screen Shot 2020-11-09 at 3 29 38 PM](https://user-images.githubusercontent.com/68430564/98592907-646e6400-22a0-11eb-9cf9-dc571e6dacc3.png)

 
And generates the following bpmn:
```xml
<bpmn:dataStoreReference id="DataStoreReference_11xnvy1" name="Data store" />
```
