### ISSUE TITLE
Task Markers

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1248]
![image](https://user-images.githubusercontent.com/535300/98559111-1125f280-225b-11eb-9b97-da3e1138b4b2.png)

![image](https://user-images.githubusercontent.com/535300/98560441-a1b10280-225c-11eb-9804-cfa37e87febf.png)

**Comment by vehikl-jacare** [comment]
We already have support for parallel and sequential task markers, but there is no way to toggle it through the UI:

![Screen Shot 2020-11-09 at 3 50 43 PM](https://user-images.githubusercontent.com/68430564/98594945-566e1280-22a3-11eb-9f82-aeecc1246b10.png)

Adding the loop marker would be very similar to adding the other two markers. Code exists for setting markers in the `hasMarkers.js` mixin, and adding the loop marker would require code that handles the following BPMN:

```xml
<bpmn:task id="node1" name="Loop">
  <bpmn:standardLoopCharacteristics />
</bpmn:task>
```

And makes the appropriate call to `this.$set(this.markers.bottomCenter, 'loop', loopIcon)` to add the loop icon:
![Screen Shot 2020-11-09 at 4 06 37 PM](https://user-images.githubusercontent.com/68430564/98596518-8d452800-22a5-11eb-886e-c2356af4b4ec.png)

Similar idea for the compensation marker:
```xml
<bpmn:task id="node1" name="Compensation" isForCompensation="true"/>
```
![Screen Shot 2020-11-09 at 4 21 08 PM](https://user-images.githubusercontent.com/68430564/98597824-946d3580-22a7-11eb-91f2-c451af536821.png)
