### ISSUE TITLE
Task Icons

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1249]
We'd like to able to change the icon icon for any task with a custom one. This icon will replace the icon in the top left of the task element and this functionality needs to be available to Form, Manual, Call Activity and Service tasks.

**Comment by vehikl-jacare** [comment]
On hold: Waiting for clarification on how to implement the icon tool in core, and whether the selected task icon should be added to the task, or if it should replace the task's existing icon.

**Comment by velkymx** [comment]
@vehikl-jacare description updated

**Comment by velkymx** [comment]
Crown mock up. 

Icon is fontawesome.com drafting-compass

Note the color order.

![image](https://user-images.githubusercontent.com/535300/100634855-a78e8680-32e4-11eb-8e3e-0fe137edb49c.png)
