### ISSUE TITLE
Color Picker Invalid BPMN

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1250]
attribute 'color' is not supported

**Steps to Reproduce:**

Create process
Create task
Change task color with pallete color
Try start new Request

**Current Behavior:**

In Process Modeler, adding a color to a task using the new Color Palette option, will throw a bpmn validation error about the COLOR tag. This will prevent the process to be started from the Request button and show the validation warning icon in the Process list. This behavior obviously undermines the whole Color option.

Side note, a process ´broken´this way can still be started via a web entry on a start event. So looks like its just our UI performing validation and preventing the start.

**Comment by vehikl-jacare** [comment]
We determined that adding the "pm" namespace to the color property will fix this issue. i.e "pm:color" instead of "color" as the property name. 
https://github.com/ProcessMaker/modeler/blob/01ea61d0ba7ad7744ed634e6be6a0e234e406f1a/src/components/crown/crownButtons/crownColorDropdown.vue#L90-L91

**Comment by vehikl-jacare** [comment]
This requires a change in the [processmaker-bpmn-moddle repository](https://github.com/ProcessMaker/processmaker-bpmn-moddle). We'll be adding an attribute to the BaseElement to explicitly declare 'color' as part of the 'pm' namespace.

For example:
```json
{
      "name": "BaseElement",
      "extends": [
        "bpmn:BaseElement"
      ],
      "isAbstract": true,
      "properties": [
        {
          "name": "color",
          "isAttr": true,
          "type": "String"
        }
      ]
    }
```
