### ISSUE TITLE
Errors when I change the type of control in the modeler

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1314]
Steps to Reproduce:

1. Log in
2. Create a new process
3. Create a start event and task
4. Click on start event
5. Change to start timer event

**Current Behavior:**
when I change the type of control in the modeler, an alert and errors are shown in console

`Cannot read property 'getSel' of null`

replicates with all designer controls, start, task.

**Expected Behavior:**
It should not show errors or alerts when we change the type of control.

**Comment by boliviacoca** [comment]
This issue has not been reproduced in RT 4.1 Rc8, QA confirmed and closed it, I'm closing this one as well.

Thanks
