### ISSUE TITLE
It is not possible save the process with data object

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1316]
Steps to Reproduce:

1. Create a process
2. Add pool
3. Add two lanes
4. Add data object component inside the lane
5. Change name of data object
6. Press save button

Current Behavior:
Error appears when you press save the process

Expected Behavior:
It should save all changes without errors

https://user-images.githubusercontent.com/535300/103666563-a4ad3400-4f29-11eb-8d37-8b54edb63dcc.mp4

**Comment by vehikl-jacare** [comment]
Pools and pool lanes incorrectly had `flowNodeReferences` to Data Stores and Data Objects. These have now been removed and it seems to resolve the underlying issue.
