### ISSUE TITLE
Boundary Event Corrupts Process

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1317]
Steps to Reproduce:

1. Create a process
2. Add a pool with:
3. Start Even -> Task with boundary event -> intermediate signal town event
4. Press Save button
5. Add another pool with :
6. Start Signal Event -> Task with boundary event -> End Event
7. Press Save
8. Delete the boundary event
9. Delete the last pool
10. Press Save button
11. Refresh the page
12. Appears a icon loading
13. Add other controls are not displayed

Current Behavior:
The process get corrupt and it is not possible add other controls inside, only the icon loading appears

https://user-images.githubusercontent.com/535300/103668966-9f9db400-4f2c-11eb-8a2f-0cda9563e506.mp4

**Comment by vehikl-jacare** [comment]
This happens because the boundary event is silently duplicated in the top pool, but orphaned from the correct parent node.

We then end up with two identical boundary event definitions in the diagram, for example, `node_4`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:pm="http://processmaker.com/BPMN/2.0/Schema.xsd" id="Definitions_03dabax" targetNamespace="http://bpmn.io/schema/bpmn" exporter="ProcessMaker Modeler" exporterVersion="1.0">
  <bpmn:process id="Process_1" isExecutable="true">
    <bpmn:boundaryEvent id="node_4" name="Boundary Conditional Event" attachedToRef="node_3">
      <bpmn:conditionalEventDefinition>
        <bpmn:condition xsi:type="bpmn:tFormalExpression"></bpmn:condition>
      </bpmn:conditionalEventDefinition>
    </bpmn:boundaryEvent>
  </bpmn:process>
  <bpmn:collaboration id="collaboration_0">
    <bpmn:participant id="node_1" name="Pool" processRef="Process_1" />
    <bpmn:participant id="node_2" name="Pool" processRef="process_2" />
  </bpmn:collaboration>
  <bpmn:process id="process_2">
    <bpmn:task id="node_3" name="Form Task" pm:assignment="requester" />
    <bpmn:boundaryEvent id="node_4" name="Boundary Conditional Event" attachedToRef="node_3">
      <bpmn:conditionalEventDefinition>
        <bpmn:condition xsi:type="bpmn:tFormalExpression"></bpmn:condition>
      </bpmn:conditionalEventDefinition>
    </bpmn:boundaryEvent>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <!-- diagram details omitted from the snippet -->
</bpmn:definitions>
```

**Comment by vehikl-jacare** [comment]
This happens because we set the pool on the `add-node` event, and the fix is to set the pool to the parent node's pool reference during the creation of the boundary event.
