### ISSUE TITLE
Switching Task Types Adds Errors

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1318]
Steps to Reproduce:

1. Create a process with some tasks
2. Select a task and make it a Sub Process
3. Add a Boundary event (ej.: Boundary Message Event)
4. Make sure your design has no validation errors
5. Change the sub-process to Task form
6. Save the changes
7. Refresh the page
8. The boundary event wast not deleted
9. Open logs of auto-validation
10. These warnings/errors don't disappear

Current Behavior:
Validation errors of events do not disappear if I delete this event from a task on the process

Expected Behavior:
Auto-validation should not show errors if the process does have errors

https://user-images.githubusercontent.com/535300/103669366-1c309280-4f2d-11eb-9b94-4d22b0a7be69.mp4

Options

**Comment by vehikl-jacare** [comment]
This issue is related to a reference to the Boundary Event left over when the original element has been replaced by one of a new type.

We have updated the replacement and delete logic to handle boundary events correctly.
