### ISSUE TITLE
Merge Flows in Crown

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1319]
When choosing a flow in the CROWN I'd like there to be only a single crown icon. Once the link is connected to an element, and depending on the element type, the link should automatically change to the correct link type (solid, dashed or dotted)

![image](https://user-images.githubusercontent.com/535300/103669906-c7414c00-4f2d-11eb-9403-247f15f25aa2.png)

**Comment by vehikl-jacare** [comment]
We've been doing some exploratory work in `1319-merge-flows` but are parking it for now to look at higher-priority tasks.

Notes for when we resume - the basic idea is to: 
 - add a new generic placeholder element (`'processmaker-modeler-generic-flow'`)
 - draw the interim lines using the orthogonal router
 - extract validity logic from `sequenceFlow`, `messageFlow`, and `dataFlow` to modules
 - use the extracted validity logic inside the generic flow to determine if the `source` and `target` nodes can form a valid flow, and if so, of what type
 - replace the placeholder element with a valid flow element of the type just determined.
