### ISSUE TITLE
Import Not Rendering

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#141]
When I import the XML it doesn't render.

Should be:

![screenshot 2019-01-16 08 08 11](https://user-images.githubusercontent.com/535300/51261856-f687d880-1965-11e9-8065-5bb4032a7ef8.png)

Is

![screenshot 2019-01-16 08 08 36](https://user-images.githubusercontent.com/535300/51261855-f687d880-1965-11e9-863f-405a30e6bc60.png)

**Comment by velkymx** [comment]
[Gmail_approval_template_v2.bpmn.txt](https://github.com/ProcessMaker/modeler/files/2765030/Gmail_approval_template_v2.bpmn.txt)

**Comment by velkymx** [comment]
It's getting closer...

![screenshot 2019-01-18 14 35 00](https://user-images.githubusercontent.com/535300/51416409-49ac8780-1b2e-11e9-9ba5-73d0fba09083.png)

![screenshot 2019-01-18 14 34 28](https://user-images.githubusercontent.com/535300/51416410-49ac8780-1b2e-11e9-9020-311ac54d21f2.png)

**Comment by chipit24** [comment]
@velkymx can you send me the XML/BPMN file for that process? It seems like I already have it, but just want to make sure. When I upload my process to the modeler I get this:

<img width="747" alt="screen shot 2019-01-18 at 5 39 30 pm" src="https://user-images.githubusercontent.com/7561061/51416581-2098f080-1b48-11e9-86b7-f95cdf3d987d.png">

Which renders exactly how I expect. The intermediate throw event and message flow are not yet supported and aren't rendered.
