### ISSUE TITLE
Unable to Create Node

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#161]
If I delete a node I am unable to bring a new on the canvas

https://www.dropbox.com/s/2oejpc4zw3dat50/cannot_bring_on_new_node_after_deleteing_old_one.mp4?dl=0

**Comment by tuantruong625** [comment]
Having trouble reproducing this issue. Could you provide the steps to reproduce this ?

**Comment by milaendo** [comment]
To reproduce:

create a pool with three lanes, create a few nodes and divide them throughout the lanes, with two gateways on the last lane. delete the last node that connects to the end event, then try to bring a new node on the canvas. please let me know if you need anymore information.
