### ISSUE TITLE
Importing xml file renders improperly

### ISSUE THREAD

**Issue by PMQABen** [ProcessMaker/modeler#168]
(This is different from #141)

1. Open modeler
2. Attach the following file: [bpmnProcess.xml.txt](https://github.com/ProcessMaker/modeler/files/2789405/bpmnProcess.xml.txt)

What you should see:
![image](https://user-images.githubusercontent.com/28575916/51642276-7b05c880-1f1d-11e9-8cab-0090d32d6f19.png)

What displays:
![image](https://user-images.githubusercontent.com/28575916/51642098-003cad80-1f1d-11e9-8961-5fd9ebe51f25.png)

Unsure why this occurs, all browsers.

**Comment by tuantruong625** [comment]
I recreated the process above in our modeler then exported and imported and had no issues. Also I imported the xml from our modeler into Camunda and no issues.

I noticed the extension on the file is .txt and renamed the file to have that extension and it does not effect the rendering of the process.

Could you provide the exact steps to reproduce this issue ?

@PMQABen

**Comment by PMQABen** [comment]
I had to rename it to .txt because github does not allow attaching xml files. I've attached a zip file of an mp4 video that shows a way to replicate this issue:

[Untitled2-480.mp4.zip](https://github.com/ProcessMaker/modeler/files/2793616/Untitled2-480.mp4.zip)

**Comment by caleeli** [comment]
Also take a look to the leave of absence request:

[LeaveAbsenceRequest.bpmn.zip](https://github.com/ProcessMaker/modeler/files/2808231/LeaveAbsenceRequest.bpmn.zip)

**Comment by vehikl-morning-mob** [comment]
Root cause: when dropping an element inside a pool in Firefox, the calculated offset are relative to the pool and the drop relative is relative to the paper origin. Interestingly, Firefox handles the drop event more closely to spec for the offset attributes.
