### ISSUE TITLE
What are valid association attributes ?

### ISSUE THREAD

**Issue by vehikl-morning-mob** [ProcessMaker/modeler#181]
![image](https://user-images.githubusercontent.com/39924126/52086456-f34f3800-2574-11e9-9120-ecb653695f40.png)

Associations currently have a name attribute, however Camunda complains about it being an unknown attribute. The spec says that names aren't properties of associations. Should we remove 'name' from the attribute list in modeler for Associations?

As well, currently modeler doesn't expose the association direction, however the spec says it should exist. Should 'direction' be added?

Finally, is the expression property a valid attribute should it be removed or kept?

**Comment by caleeli** [comment]
An association does not have "**name**" attribute. It must be removed.
An association does not have "**expression**" attribute. It must be removed.
According to the XSD, the association direction is not required but it has a default value "None". It could be desirable to include this attribute (Possible values: None, One, Both)

```
Table 8.26 – Association XML schema
<xsd:element name="association" type="tAssociation" substitutionGroup="artifact"/> <xsd:complexType name="tAssociation">
<xsd:complexContent> <xsd:extension base="tArtifact">
<xsd:attribute name="sourceRef" type="xsd:QName" use="required"/>
<xsd:attribute name="targetRef" type="xsd:QName" use="required"/>
<xsd:attribute name="associationDirection" type="tAssociationDirection" default="None"/>
</xsd:extension> </xsd:complexContent>
</xsd:complexType>

<xsd:simpleType name="tAssociationDirection"> <xsd:restriction base="xsd:string">
<xsd:enumeration value="None"/> <xsd:enumeration value="One"/> <xsd:enumeration value="Both"/> </xsd:restriction>
</xsd:simpleType>
```

**Comment by velkymx** [comment]
I think that if the spec calls for the direction that we should add it.
