### ISSUE TITLE
Inspector Scrolling

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#186]
When the content of the inspector is greater than the space, the inspector should scroll.

**Comment by velkymx** [comment]
This doesn't seem right. Is the inspector scrolling or the toolbar? Should be the inspector.

**Comment by chipit24** [comment]
I got inspector (on the right) and toolbar mixed up. In any case, it makes sense that both have the same scrolling behaviour. I'll create a new branch to fix scrolling in the inspector panel as well.
