### ISSUE TITLE
Annotation Overflow Issue

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#187]
The following image is the default Text Annotation element after placing it into a Process model. Notice how the bracket and text don't like up correctly.

![image](https://user-images.githubusercontent.com/535300/52226613-50dbd100-2862-11e9-9723-cb9b6ef27c19.png)

**Comment by chipit24** [comment]
@velkymx After merging PRs, this no longer appears to be an issue on develop.
