### ISSUE TITLE
Cannot Delete Flow

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#194]
Current process                
 
![image](https://user-images.githubusercontent.com/535300/52354814-fb303180-29e5-11e9-9325-7639a5eb0728.png)

When attempting to add new task cannot delete flow
 
![image](https://user-images.githubusercontent.com/535300/52354822-ff5c4f00-29e5-11e9-80e4-3c320843d0cc.png)

Allows us to delete if it is not in straight connection

![image](https://user-images.githubusercontent.com/535300/52354838-06835d00-29e6-11e9-8ed0-03bbb45f0045.png)

**Comment by chipit24** [comment]
@velkymx I could not reproduce this using the latest `develop` build both with the standalone modeler and within bpm. There were no issues adding and deleting sequence flows. Can you provide more details?
