### ISSUE TITLE
Parallel Gateway

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#195]
As a designer I would like a Parallel Gateway to represent two concurrent tasks in workflow.

https://www.lucidchart.com/pages/bpmn-gateway-types?a=1#section_2

https://docs.camunda.org/manual/7.8/reference/bpmn20/gateways/parallel-gateway/

**Comment by velkymx** [comment]
Let's explore what this entails and discuss before starting.

**Comment by tuantruong625** [comment]
**Parallel Gateway**
- Creates parallel paths without checking any conditions
- Inherits attributes and model associations of gateway

> Business Process Model and Notation, v2.0 - page 294

- Adds no additional attributes or model associations 

> Business Process Model and Notation, v2.0 - page 295

**Shape**
- Marker that is in the shape of a plus sign and is placed within the gateway diamond

> Business Process Model and Notation, v2.0 - page 293

**Shape Attributes**
- id
- name
- gatewayDirection (only converging and diverging)

> Business Process Model and Notation, v2.0 - page 6

**Comment by velkymx** [comment]
Make sure the that we require a merge gateway
