### ISSUE TITLE
BPMN Lint

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#196]
Let's explore how to use and implement this linter to validate the BPMN. Let's discuss before any implementation.

https://github.com/bpmn-io/bpmnlint

https://github.com/camunda/bpmnlint-plugin-camunda#readme

**Comment by velkymx** [comment]
When there are errors, update the footer (with the green check) to show that there is an error and then count. When you click on the error, I'd like a drawer to slide up and show the itemized list of errors. Can we highlight (maybe with an icon) which element is failing.

**Comment by chipit24** [comment]
Work for this has been merged, see https://github.com/ProcessMaker/modeler/pull/206#issuecomment-464118798.
