### ISSUE TITLE
Tasks should be able to connect to exclusive gateways

### ISSUE THREAD

**Issue by tdondich** [ProcessMaker/modeler#20]
Connecting via flow needs to be allowed from task to exclusive gateway.  And exclusive gateway also needs to allow connecting to tasks.

However, the exclusive gateway can only have two outbound flows and only one inbound flow. We should enforce these rules.

@enriquecolosa , do you agree with these rules? What should the behavior be if you attempt to do something against these rules?

**Comment by enriquecolosa** [comment]
About rules some clarifications:

1. Exclusive Gateways work different depending the work are doing over the process, can act like divergent gateways (forking the flow) or convergent gateways (merging some flows).
2. Divergent Gateways rules say that only need to support one in coming flow, and 2 or more out coming flows (this rule is true, but only from the point of view of the execution (running time). By example see the following scenario is totally valid:
![screen shot 2018-10-23 at 2 53 18 pm](https://user-images.githubusercontent.com/6341099/47383843-94efff00-d6d3-11e8-979d-0951dc067b2f.png)
We are expecting at execution time the gateway will receive only one token at a time, but that token can be present from different sources. Visually and in designing time there's 2 incoming flow drawn.
3. Convergent Gateways rules say that only one out coming flow should be present and 2 or more incoming flows are expected.

About the behavior when a flow can be connected or not we are expecting the following:

- Target element will be highlighted green when a valid connection is possible
- Target element will be highlighted red when a valid connection isn't possible.
- A console error message will be throw when an invalid connection is attempt.

@tuantruong625 let me know if this comments are reflecting our call and answer your questions.
