### ISSUE TITLE
bpm definition is not valid

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#203]
_#1306 (potentially related)_

1. Create a Process
2. Change the Process Identifier to use a space (for example: `ProcessId` » `Process Id`)
3. Save the Process
4. Reload the page
5. Try saving again

**Result:**

```
The bpm definition is not valid

PUT http://bpm4.local.processmaker.com/api/1.0/processes/5 422 (Unprocessable Entity)

0: "Error 1824 (Line:3):Element '{http://www.omg.org/spec/BPMN/20100524/MODEL}process', attribute 'id': 'Process Id' is not a valid value of the atomic type 'xs:ID'."
1: "Error 1824 (Line:5):Element '{http://www.omg.org/spec/BPMN/20100524/DI}BPMNPlane', attribute 'bpmnElement': 'Process Id' is not a valid value of the atomic type 'xs:QName'."
length: 2
```
[process.mp4.zip](https://github.com/ProcessMaker/bpm/files/2818929/process.mp4.zip)

Even removing the space and saving, the user still runs into a 422.

**Comment by chipit24** [comment]
For reference, #1306 refers to this issue: https://github.com/ProcessMaker/bpm/issues/1306.

**Comment by chipit24** [comment]
The standalone app has no issue with downloading or uploading diagrams with spaces in IDs. 

There doesn't seem to be a [bpmnlint rule](https://github.com/bpmn-io/bpmnlint/tree/master/rules) for validating spaces in node IDs, but I'm sure it's something we can add. The question is, how should we implement this validation? Should it be linked to bpmnlint, or added to individual node configs, or something else?

I think this issue would have to be handled in bpm in https://github.com/ProcessMaker/bpm/issues/1306. As for frontend validation, I think it makes sense to build something on top of https://github.com/ProcessMaker/modeler/pull/206.

I'm not too sure if spaces in IDs is valid or not. The spec only mentions that it needs to be a string, and isn't even required if the node isn't referenced by something else.

It does have some blurb about QName on page 477 (507 in PDF):
> The BPMN XSD utilizes IDREFs wherever possible and resorts to QName only when references can span files. In both situations however, the reference is still based on IDs.

Here, QNames can't have spaces or start with numbers. When testing this in Camunda, it throws an error saying "Id must be a valid QName".
