### ISSUE TITLE
Advanced Timer Start Event configurations

### ISSUE THREAD

**Issue by danloa** [ProcessMaker/modeler#213]
The Timer Start Event  must have the following configurations:

-----------------------------------------------------------
Show a checkbox with the label **Is Periodic** (true/false)
-  If Checked Show a list with options: hourly, daily, monthly, Every
     If user selects Hourly show: start date, end date, minute
     If user selects  Daily show: start date, end date, hour, minute, day of week 
     If user selects Monthly show:  start date, end date, day, hour, minute, month
     if user selects Every show: hour, minute

- Else show Date Time
-----------------------------------------------------------

The following screenshots can be used as a guide.

**Hourly:**     
![timer1](https://user-images.githubusercontent.com/14875032/52563825-d7e7f680-2dd8-11e9-9bff-90db4d5e0046.png)     

**Daily:**
![timer2](https://user-images.githubusercontent.com/14875032/52563823-d7e7f680-2dd8-11e9-9efb-3063aeb40a56.png)

**Monthly:**
![timer3](https://user-images.githubusercontent.com/14875032/52563821-d74f6000-2dd8-11e9-8497-a3a1d58ad0f2.png)

**Every:**
![timer4](https://user-images.githubusercontent.com/14875032/52563819-d74f6000-2dd8-11e9-9d27-bd2039cf7443.png)

### One date/time:
![timer5](https://user-images.githubusercontent.com/14875032/52563818-d74f6000-2dd8-11e9-8d2c-113c335dcb79.png)

**Comment by velkymx** [comment]
![screenshot 2019-02-11 09 37 26](https://user-images.githubusercontent.com/535300/52581867-abd07380-2de0-11e9-8eab-def22dbd9829.png)

**Comment by velkymx** [comment]
![screenshot 2019-02-11 09 38 34](https://user-images.githubusercontent.com/535300/52581914-cefb2300-2de0-11e9-8455-8396b7e18ba5.png)

**Comment by chipit24** [comment]
Closing ticket as associated PR has been merged. @caleeli For reference, you can use one of the keywords described here to have issues auto-close when the PR is merged: https://help.github.com/articles/closing-issues-using-keywords/.
