### ISSUE TITLE
BPMN Lint : Display Itemized List of Errors

### ISSUE THREAD

**Issue by tuantruong625** [ProcessMaker/modeler#215]
Reference #196 

Initially the footer will show a count of the errors. When the user clicks on the footer, a drawer will slide up and display the itemized list of errors.

Example of the contents of the error.

```
'end-event-required': [
    {
      category: 'error',
      id: 'Process_1',
      message: 'Process is missing end event',
    },
  ],
```
![problem-panel-modeler](https://user-images.githubusercontent.com/26545455/52588896-8d33a200-2e0b-11e9-8eb1-876e7d5f3a0a.png)

**Comment by chipit24** [comment]
Associated PR has been merged, closing issue.
