### ISSUE TITLE
Inspector Accordion

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#221]
I want to be able to group elements in the inspector sidebar on right. Group name, icon and id, by default only open the configuration "tab".

<img width="214" alt="screenshot 2019-02-12 08 13 57" src="https://user-images.githubusercontent.com/535300/52649965-27dcc100-2e9e-11e9-8af8-10d7972f2e28.png">

**Comment by velkymx** [comment]
https://fontawesome.com/icons?d=gallery&m=free

**Comment by tdondich** [comment]
You can totally use the concept of form pages for grouping.  And include meta data in each page for the icon to use.  This will require modifying the vue form renderer that's used for the inspector in order to render properly.

**Comment by velkymx** [comment]
Make this a form element. https://github.com/ProcessMaker/vue-form-elements/issues/21
