### ISSUE TITLE
Intermediate Timer Event configurations

### ISSUE THREAD

**Issue by caleeli** [ProcessMaker/modeler#225]
Implement the intermediate timer event flow element.

In normal flow the Timer Intermediate Event acts as a delay mechanism based on a specific time-date or time delay. This Event MUST be displayed with a clock marker:

![image](https://user-images.githubusercontent.com/8028650/52742641-8f823180-2fae-11e9-9adf-bb0b52cd9019.png)

**Comment by chipit24** [comment]
Closing ticket as associated PR has been merged.

@caleeli For reference, you can use one of the keywords described here to have issues auto-close when the PR is merged: https://help.github.com/articles/closing-issues-using-keywords/.

For our PRs, we always put `Fixes #{issue_number}`.
