### ISSUE TITLE
BPMNLint causes error in BPM project

### ISSUE THREAD

**Issue by caleeli** [ProcessMaker/modeler#229]
Looks like the bpmnlint module is not transpiled to ES5:

![image](https://user-images.githubusercontent.com/8028650/53016733-a3052080-3424-11e9-8b34-406fbb6be49f.png)

**Comment by velkymx** [comment]
Use this issues to test: https://github.com/ProcessMaker/bpm/issues/1399

When you push it will auto-build to the cloud at: http://feature-1399.bpm4.qa.processmaker.net
