### ISSUE TITLE
Event Based Gateway

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#261]
Review and post your interpretation in the comments.

https://docs.camunda.org/manual/7.6/reference/bpmn20/gateways/event-based-gateway/

**Comment by chipit24** [comment]
Event-based gateway will have the following symbol (the standard diamond but with a "catch multiple intermediate event" in the middle):

<img width="84" alt="screen shot 2019-03-01 at 10 04 25 am" src="https://user-images.githubusercontent.com/7561061/53646538-6a75fb80-3c09-11e9-87a4-027ad1ea1f64.png">

The event-based gateway will follow these rules:
* Must have 2 or more outgoing sequence flows, and those flows must not have a `conditionExpression` property.
* The outgoing targets must be either intermediate events or receive tasks.
  - If Message Intermediate Events are used in the configuration, then Receive Tasks MUST NOT be used in that configuration and vice versa.
* Target elements in an Event Gateway configuration MUST NOT have any additional incoming Sequence Flows (other than that from the Event Gateway).

Also, from the spec:
> When the first Event in the Event Gateway configuration is triggered, then the path that follows that Event will used (a token will be sent down the Event’s outgoing Sequence Flows). All the remaining paths of the Event Gateway configuration will no longer be valid. Basically, the Event Gateway configuration is a race condition where the first Event that is triggered wins.

The event-based gateway has the following additional properties:
<img width="819" alt="screen shot 2019-03-01 at 10 13 42 am" src="https://user-images.githubusercontent.com/7561061/53647106-cc833080-3c0a-11e9-906d-6db891c17d3e.png">
