### ISSUE TITLE
Inclusive Gateways

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#262]
https://docs.camunda.org/manual/7.6/reference/bpmn20/gateways/inclusive-gateway/

**Comment by tuantruong625** [comment]
**Inclusive Gateway**
- combination of an exclusive and a parallel gateway. 
- can define conditions on outgoing sequence flows
- **can receive more than one sequence flow**

Attributes
- id
- name
- gatewayDirection
