### ISSUE TITLE
Inclusive Gateway - Converging/Diverging Constrains are not being validated

### ISSUE THREAD

**Issue by caleeli** [ProcessMaker/modeler#268]
The gateway direction (Converging | Diverging) adds constraints on how the Gateway MAY be used.

• Converging: This Gateway MAY have multiple incoming Sequence Flows but MUST have no more than one (1) outgoing Sequence Flow.
• Diverging: This Gateway MAY have multiple outgoing Sequence Flows but MUST have no more than one (1) incoming Sequence Flow.

At this moments that is not being validated.

https://processmaker.slack.com/files/U078GPWPQ/FGL4K5X1B/convergingconstraintnotvalidated.mov

**Comment by chipit24** [comment]
WIP branch put up, blocked until https://github.com/ProcessMaker/modeler/issues/268 is merged.
