### ISSUE TITLE
Autolint

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#273]
We'd like the linter to run automatically when there is a change in the canvas.

**Comment by chipit24** [comment]
@velkymx In this case, the "Validate BPMN" button will become obsolete and we can remove it, correct?

With this change, the red border/highlight will probably appear right away on many elements, and I think this can be improved:
* Only show highlight after clicking on element in the list of errors, and/or
* Show a less obtrusive notice, such as an icon off to the side of the element

**Comment by velkymx** [comment]
- [ ] Remove the Validate BPMN button
- [ ] Add bootstrap toggle (default to on)
- [ ] When toggle is changed from off to on run linter
