### ISSUE TITLE
Deleted Node Garbage Collection

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#295]
Noticing that even if you delete nodes as part of building a flow, it will still save the XML with data for those nodes.

Which can lead to instances where the validator will complain that a deleted node is missing a label.

**Comment by PMQABen** [comment]
1. Create a flow with many control nodes.
2. Delete all the control nodes.
3. Create a simple flow, just start to end.
4. Download the xml file.

Attached example file: [bpmnProcess.xml.txt](https://github.com/ProcessMaker/modeler/files/2979476/bpmnProcess.xml.txt)
_(Be sure to rename the file to xml)_

![image](https://user-images.githubusercontent.com/28575916/54550582-7e3f9280-4969-11e9-82c9-fd477fe466fd.png)

**Comment by chipit24** [comment]
@velkymx @PMQABen I can't reproduce the problem. Maybe it's already fixed on the latest `develop` branch? If not, can you provide the _exact_ steps you took to reproduce the problem?
