### ISSUE TITLE
Multiselect Flow Elements

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#3]
Add the ability to drag a box with the mouse to multiselect flow elements on the canvas. Then, once select you should be able to drag all selected elements as one. 

![image](https://user-images.githubusercontent.com/535300/46636539-448e7400-cb0d-11e8-8fb6-3a8a88f56925.png)

**Comment by chipit24** [comment]
Clicking and dragging currently pans the paper element. I can add a lasso/multi-select button that allows the user to drag a select box over multiple elements.

**Comment by velkymx** [comment]
@chipit24 we don't want the lasso. We want it to always be on.

**Comment by tdondich** [comment]
Let's de-prioritize this, until we have a better determination of how to "toggle" the behavior on off, or special key bindings to toggle this.

**Comment by tdondich** [comment]
We're closing and removing this.  Not necessary for launch.
