### ISSUE TITLE
Date Time browser issue

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#320]
On Firefox and MS Edge, the time for the "date/time" section of the Intermediate Timer Event gets cut off on the screen (only shows 2-3 digits, not all 4) 

1. Open Firefox or MSE
1. Create a new Process (or open existing)
1. Add an Intermediate Timer Event to the modeler
1. Click on the event, and change Timing Control from "Delay" to "Date/Time"

**Comment by tuantruong625** [comment]
@velkymx Can't reproduce, could you provide more details?

**Comment by velkymx** [comment]
@PMQABen can you provide screenshots of this behavior?
