### ISSUE TITLE
Save flow vertices into the BPMN

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#396]
Allow saving the flow vertices into the bpmn file under the processmaker namespace

And then the ability to parse those vertices and use them in the link routers when importing a bpmn file

![image](https://user-images.githubusercontent.com/535300/57961346-2d91da80-78c3-11e9-98b2-60b00b4f9ce8.png)

**Comment by chipit24** [comment]
@velkymx I'm able to add and parse / save vertices I add. Undo / redo also works as expected when modifying vertices. They are saved as standard waypoints, e.g.:
```
<bpmndi:BPMNEdge id="node_3_di" bpmnElement="node_3">
  <di:waypoint x="168" y="150" />
  <di:waypoint x="168" y="80" />
  <di:waypoint x="310" y="80" />
  <di:waypoint x="430" y="80" />
  <di:waypoint x="430" y="231" />
</bpmndi:BPMNEdge>
```

What do you mean by saving under the processmaker namespace?

**Comment by velkymx** [comment]
Yes. Save theme as a ProcessMaker only BPMN attribute.

**Comment by chipit24** [comment]
@velkymx Can I get more clarification on this? I'm not sure what you mean by saving under the ProcessMaker namespace or attribute.

You want the `x` and `y` attributes on the waypoint diagram elements to be saved under the pm namespace? Like:

```
<bpmndi:BPMNEdge id="node_3_di" bpmnElement="node_3">
  <di:waypoint pm:x="168" pm:y="150" />
  <di:waypoint pm:x="168" pm:y="80" />
</bpmndi:BPMNEdge>
```

This will create some compatibility issues with other tools, but I'm assuming that won't be an issue. And if importing a diagram from other tools, should these attributes be converted to use the pm namespace?

**Comment by tdondich** [comment]
Heya!  I'm going to chime in here.  I honestly didn't realize the waypoint allowed for more than two points.  So yeah, let's NOT store it in the pm namespace @velkymx .  The waypoint is totally fine.  I thin kthough the ticket is saying we are NOT storing the waypoints to match the custom vertices of the flows.  And if we are, we're not rendering them correctly on load.

**Comment by velkymx** [comment]
![image](https://user-images.githubusercontent.com/535300/59527505-9e132380-8e90-11e9-8366-db447699f88f.png)

**Comment by chipit24** [comment]
Tested this again and vertices are working correctly. Here is a video adding / remove / modifying vertices, and they are persisted after refresh: https://www.dropbox.com/s/pseiqea3e9hi942/vertices_working.mov?dl=0.

**Comment by chipit24** [comment]
Closing as this seems to be working as expected (see above comment).

**Comment by chipit24** [comment]
I've tried multiple combinations of creating sequence flows and still can't find any issues. I did discover a new bug though:
* Modifications to the association flow vertices are not saved to the undo/redo stack (they are persisted if you save and refresh, though).

I've created a new issue for that: https://github.com/ProcessMaker/modeler/issues/439.

Re-creating the process form the screenshot in the issue above:
<img width="893" alt="Screen Shot 2019-06-19 at 11 00 05 AM" src="https://user-images.githubusercontent.com/7561061/59778519-a5697100-9284-11e9-8d7d-1d4abf97ae75.png">

Random testing:
<img width="807" alt="Screen Shot 2019-06-19 at 11 14 05 AM" src="https://user-images.githubusercontent.com/7561061/59778468-89fe6600-9284-11e9-98da-188d23a50bb4.png">

@velkymx If you (or anyone from QA) can provide some steps to re-create the problem with this, please let me know.

I've also noticed that message flows (between processes / pools) causes a server error when trying to save. Not sure if this is a known issue with the backend though.
