### ISSUE TITLE
Text Annotation Element

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#4]
When I click on the text icon in the flow menu, I want to be able to drag a text annotation onto the canvas. I need to be able to then click on the flow element and edit the text in the inspector pane.

**Comment by tuantruong625** [comment]
In Camunda Modeler, the text annotation element are handled within the crown.

<img width="272" alt="screen shot 2018-10-15 at 2 42 26 pm" src="https://user-images.githubusercontent.com/26545455/46971021-dad01600-d088-11e8-8324-e3eedc29c08b.png">
55/46970960-a9efe100-d088-11e8-83b0-b686a5483f4b.png">

To clarify we want to handle the text annotations  as draggable items from the flow menu ?
