### ISSUE TITLE
Missing Translations

### ISSUE THREAD

**Issue by milaendo** [ProcessMaker/modeler#435]
While testing German translations I am seeing this English strings in the modeler

- [ ] Please click On to select a date.
- [ ] New Task
- [ ] The id field should be unique across all elements in the diagram, ex. id_1.
- [ ] New Manual task
- [ ] New Call Activity 
- [ ] New Exclusive gateway 
- [ ] New Inclusive gateway 
- [ ] New Parallel gateway 
- [ ] New Pool
- [ ] New Event based gateway 
- [ ] Filter

![Screen Shot 2019-06-17 at 10 30 20 AM](https://user-images.githubusercontent.com/29641725/59624179-ee85bd80-90ea-11e9-8144-b3f81f5ce44e.png)

**Comment by chipit24** [comment]
@milaendo What version of modeler and processmaker was this tested against? Looking at the latest modeler source on develop, all of the above strings have already been wrapped in the `$t` translation function, except for

> The id field should be unique across all elements in the diagram, ex. id_1

But I think the `ex. id_1` part should be removed from the end to keep it consistent with the other error messages.

"New Task" has also been renamed to "Task":

```js
definition(moddle, $t) {
  return moddle.create('bpmn:Task', {
    name: $t('Task'),
  });
},
```

**Comment by chipit24** [comment]
Also, @milaendo, can you let me know how you test translations locally in processmaker? I only seem to have english translations available and don't see where to change it.

**Comment by milaendo** [comment]
@chipit24 When I test locally i delete my composer.lock/vendor files  and add these to my composer.json

  {
      "type": "vcs",
      "url": "https://github.com/ProcessMaker/spark-packages"
    },
    {
      "type": "vcs",
      "url": "https://github.com/ProcessMaker/spark-package-translations"
    }

and this to the required section: 

"processmaker/spark-packages": "*",
"processmaker/spark-package-translations": "*"

then run composer install. Next do "art" and look for the instal commands for the package package and the translation package.
