### ISSUE TITLE
UI Tweaks

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#446]
- [x] Round the corners of flow elements
- [x] Set BG color of lanes to #ebebeb
- [x] Reduce fonts in Controls and Inspector to 14px

**Comment by tuantruong625** [comment]
@chipit24  @velkymx Not really a fan of setting the background color on the pool/lane. I think leaving white looks the cleanest. Thoughts?

<img width="785" alt="Screen Shot 2019-06-25 at 4 19 46 PM" src="https://user-images.githubusercontent.com/26545455/60130561-77dd6580-9765-11e9-9969-2331e44b9091.png">

**Comment by chipit24** [comment]
My first impression is that the grey gives it a "disabled input" look. At the same time, my understanding for this change it that it's difficult for users to distinguish between the pools and the background process, and the grey background definitely helps with that. Visually, white looks better, but it doesn't solve the problem.

**Comment by tuantruong625** [comment]
Another approach could be having the dots on the grid be more predominant so there is greater separation between "what element is in a pool / lane and what is not".

**Comment by tuantruong625** [comment]
<img width="1108" alt="Screen Shot 2019-06-26 at 10 47 32 AM" src="https://user-images.githubusercontent.com/26545455/60189977-d9521280-97ff-11e9-8e2c-adf00926d4b6.png">

**Tighter Grid Size**
<img width="1108" alt="Screen Shot 2019-06-26 at 10 46 31 AM" src="https://user-images.githubusercontent.com/26545455/60189982-dc4d0300-97ff-11e9-9962-dc0504fa19e0.png">

**Comment by chipit24** [comment]
The blue outline makes it look like it's highlighted / selected. I think making the grid more distinct by reducing the grid size (more dots) is a great idea.

**Comment by velkymx** [comment]
Let's use the grey from the headers (where it says Control) it's #f7f7f7

I like the thought process around the blue. I'll run it by a few people, but for now remove it

**Comment by velkymx** [comment]
![image](https://user-images.githubusercontent.com/535300/60279878-b9c9f100-98b6-11e9-9d79-da4e806a7323.png)
[app-chrome.html.txt](https://github.com/ProcessMaker/modeler/files/3335505/app-chrome.html.txt)
