### ISSUE TITLE
Add rounded corners on flow elements

### ISSUE THREAD

**Issue by tuantruong625** [ProcessMaker/modeler#455]
- All flow element will have a slight curve on break points

**Comment by chipit24** [comment]
Specifying rounded flows creates extra vertices which causes parsing issues and renders differently in other modelers:

<img width="488" alt="Screen Shot 2019-06-28 at 4 33 26 PM" src="https://user-images.githubusercontent.com/7561061/60369695-85dbf200-99c2-11e9-9465-0f4a69cd5157.png">

<img width="573" alt="Screen Shot 2019-06-28 at 4 33 48 PM" src="https://user-images.githubusercontent.com/7561061/60369701-896f7900-99c2-11e9-88f5-c4228e1ff77c.png">
