### ISSUE TITLE
Validation border render issue with lanes

### ISSUE THREAD

**Issue by tuantruong625** [ProcessMaker/modeler#470]
**Issue**

When there is an error with lanes and the user attempts to resize pool/lane the red error borders will not update with the pool/lane and becomes fixed to the last size of the pool/lane.

**How to reproduce**
- Create a pool with a lane that has an error (missing label error)
- Resize the pool/lane

**Expected**
- Red error border adjust to the resize of the pool/lane

**Screenshot**
<img width="787" alt="Screen Shot 2019-07-08 at 4 32 23 PM" src="https://user-images.githubusercontent.com/26545455/60840694-145c2a80-a19e-11e9-9c19-f458b14d302e.png">

**Video of bug**
https://drive.google.com/open?id=1esMRws8fJjKIEb8KG8dNLhJxAUx94Yki

**Comment by JCook21** [comment]
This is reproducible in the latest modeler. I'm going to look into this.
