### ISSUE TITLE
Boundary Support

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#476]
Add support to the main task object for boundary events. 

![image](https://user-images.githubusercontent.com/535300/61228428-2167a500-a6db-11e9-9801-8e7ea04cd14a.png)

Initial icons for these events.

Boundary timer event
A boundary timer event puts a timer on the activity it is defined on. When the timer fires, the sequence flow going out the boundary event is followed.

Boundary error event
A boundary error event catches an error that is thrown within the boundaries of the activity the event is based on and continues process execution from the event.

Boundary signal event
A boundary signal event listens to a signal being fired (from within the process instance or system-wide) while the activity upon which the event is defined is active.

**PRD**
https://docs.google.com/document/d/16eWvjTExiJgGgDp1Yz5n-nrwTBfJFhRjE7JOjUq7r94/edit#

**Comment by velkymx** [comment]
No this is just a design support ticket, the functionality will come later.

**Comment by velkymx** [comment]
Icons: 

https://fontawesome.com/icons/bolt?style=solid

https://fontawesome.com/icons/clock?style=regular

https://fontawesome.com/icons/chevron-up?style=solid

We're going to need to get some of these font icons added to icomoon font. I'll keep you posted.

**Comment by velkymx** [comment]
[BPMN-SVG.zip](https://github.com/ProcessMaker/modeler/files/3442777/BPMN-SVG.zip)

These are the SVG icons

**Comment by velkymx** [comment]
- [ ] Boundary Events can be attached anywhere on a tasks.
- [ ] Use the Intermediate Timer Event control
- [ ] When attached to task, make black and white with the SVG above
- [ ] When non-interrupting the SVN should be the dashed outline

**Comment by velkymx** [comment]
Nice to have multiple boundary events.

**Comment by tuantruong625** [comment]
@velkymx Can you clarify a couple a couple of things?

When toggling between a boundary timer event and intermediate event do the properties on the element reset or do they persist when toggling between elements?

Are we displaying labels on the boundary events when attached to tasks?

<img width="442" alt="Screen Shot 2019-08-02 at 4 50 56 PM" src="https://user-images.githubusercontent.com/26545455/62398098-bbd24000-b545-11e9-8705-baf41eb574aa.png">

**Comment by velkymx** [comment]
Once a timer event is added to a task it can only be deleted.

Yes the config should continue with the boundary event.

Show the label / name
