### ISSUE TITLE
Inconsistent position of crown button on sequence flows

### ISSUE THREAD

**Issue by tuantruong625** [ProcessMaker/modeler#481]
When sequence flows are in a focused state the position of the crown buttons are inconsistent and in some cases interfere with the link tools. As shown in the screenshots below.

<img width="1110" alt="Screen Shot 2019-07-19 at 9 46 35 AM" src="https://user-images.githubusercontent.com/26545455/61539749-2c3b7600-aa0a-11e9-9d9b-d67c1bcc0a5c.png">

**Comment by lisa-fehr** [comment]
Closing. Might need a new ticket if this is still problematic on the new crown.
