### ISSUE TITLE
Toolbar Blocks Canvas

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#487]
"btn-toolbar" class gets in the way of the modeler background, cannot click and scroll

Video of issue: 

https://processmaker.atlassian.net/secure/attachment/59487/Untitled.mp4

**Comment by velkymx** [comment]
This issue has resurfaced with the addition of the mini-map

**Comment by JCook21** [comment]
This is definitely an issue but it doesn't stop me placing elements in the affected area or manipulating them. I don't see this as a blocker at all as this doesn't stop anyone from working with a process. The workaround would be to drag and re-center the process if it was impossible to work with elements in this area. Can we remove the blocker designation on this and re-prioritise it?
