### ISSUE TITLE
Invalid Definition

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#488]
Importing this file renders the process unable to be saved. Doesn't matter if it is saved blank, or if you try to build a new flow.

```
0: "DOMDocument::schemaValidate(): Element '{http://www.omg.org/spec/BPMN/20100524/MODEL}sequenceFlow': The attribute 'sourceRef' is required but missing."
```

Reproduction steps seem to be:

Create Process
Add various controls to build the flow
Save Process
Drag a Pool control onto the flow
Delete the Pool control (which will remove all other controls)
Save the Process
Reload the page, try to save again

BPMN: https://processmaker.atlassian.net/secure/attachment/59786/asdf%20%281%29.spark

**Comment by chipit24** [comment]
@velkymx Closing this issue as it was resolved in
