### ISSUE TITLE
Inclusive Gateways Fail Validation

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#489]
![image](https://user-images.githubusercontent.com/535300/61983294-ab095380-afb4-11e9-8220-70150d2191b3.png)

Description

Create a Process using Parallel & Inclusive Gateways
Ensure the Inclusive Gateways are set to the default direction of "Diverging"
Enable "Auto validate"
Try to save the Process
Reload the page, rebuild the same process, but with "Auto validate" enabled
Try to save the Process

Result:  
422 error

Expected:
Auto Validator should been able to pick this up.

Note:
Issue still occurs, but in a modified way. Inclusive gateways without more than one join will default to "diverging", even if they are connected to another Inclusive gateway set to "converging."

**Comment by chipit24** [comment]
@velkymx We weren't able to reproduce this bug. We re-created the process above and confirmed that:
 * The modeler correctly validated the gateway based on gateway direction.
 * We were able to save the process at every step, and did not get a 422 error.

**Comment by chipit24** [comment]
Closing as this is an old issue we cannot reproduce.
