### ISSUE TITLE
Node Renaming

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#490]
Steps to Reproduce:

1. Go to a process with elements
2. Change the ID of an element from the default node_n (where n is a number), so that the 'n' corresponds to the max value plus 1
2. Save the process
2. Change the ID of an element from the default node_n, so that the 'n' corresponds to the max value plus 2
2. Save the process

Example: If you have 3 elements your node should change from node_1 to node_4, then node_5

Current Behavior:
The identifier is not accepted while saving, no errors shown in the errors check
However, if we add 3 to the max value (node_6 in the example) the ID is accepted
IdentifierChange.mp4

Expected Behavior:
Every available ID should be accepted

Video: 

https://processmaker.atlassian.net/secure/attachment/60013/IdentifierChange.mp4

**Comment by chipit24** [comment]
@velkymx I didn't have any issues saving nodes with increasing numbers for the ID. I don't have access to the video, can you post another link to it?

**Comment by PMQABen** [comment]
[IdentifierChange.mp4.txt](https://github.com/ProcessMaker/modeler/files/3498743/IdentifierChange.mp4.txt)
Image attached, just gotta remove the .txt

**Comment by chipit24** [comment]
@velkymx We agree with @PMQABen; this appears to be expected behaviour.

**Comment by PMQABen** [comment]
@velkymx Since this looks to be expected behavior, I vote we close this issue.

**Comment by chipit24** [comment]
Closing as this is an old issue, and node ID generation and re-naming is working as expected.
