### ISSUE TITLE
Manual Task Inspector Screen Copy

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#492]
![image](https://user-images.githubusercontent.com/535300/61983503-66ca8300-afb5-11e9-95ab-22a9eca36725.png)

Change to:

The field label change to be called “Completed Manual Task Screen” and the help text to: “Screen to display to indicate that the manual task is completed.”

**Comment by chipit24** [comment]
@velkymx Looking at the screenshot, can you confirm you want the text "Summary screen" changed to "Completed Manual Task Screen" and "Summary screen that will be displayed when process finish with this End Event" to "Screen to display to indicate that the manual task is completed."

**Comment by chipit24** [comment]
@velkymx It appears that the text "Screen builder" and "Summary screen that will be displayed ..." is defined in the translation files for German, Spanish, French. We will need the appropriate translations to complete this feature.

**Comment by chipit24** [comment]
The copy for this has been updated to use "Screen for Input" and "Select Screen to display for this Task". There are no longer any translation warning being thrown either. Closing issue.
