### ISSUE TITLE
Mixed Gateways

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#493]
![image](https://user-images.githubusercontent.com/535300/61983553-a42f1080-afb5-11e9-878d-2d057b623c87.png)

Steps to Reproduce:

1. Go to the process modeler
1. Create a flow with a diverging and a converging gate
1. Make sure that the diverging and converging gates are different

Current Behavior:
The process runs normally

Expected Behavior:
Every diverging gate should only be able to have a converging gate of its own type

**Comment by chipit24** [comment]
@velkymx We think the validation for this could be complex, considering things like loops and multiple "nested" gateways in between two opening and closing gateways. We'll need to discuss this in more detail.

**Comment by chipit24** [comment]
Reproduced the process in the screenshot above and it still appears to work correctly. A new issue can be created when the requirements for this feature have been discussed and reprioritized.
