### ISSUE TITLE
Start Timer Event Control config

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#494]
In the Start Timer Event Control config, the days of the week selector selects the current day by default and you can't select another day without having the current days day selected. 

Here is a video

https://processmaker.atlassian.net/secure/attachment/60511/Repeat%20On.mp4

**Comment by velkymx** [comment]
https://www.dropbox.com/s/s4t6vyfa7y2jm29/Repeat%20On.mp4?dl=0

**Comment by chipit24** [comment]
@velkymx Can you clarify how this control should behave? Some questions we currently have:
 * Should one day of the week always be selected?
 * Should the current day be selected by default?
 * Should it be possible to de-select all days of the week, and if so:
 * When no days of the week are selected, is the current day assumed to be selected?

**Comment by velkymx** [comment]
Should one day of the week always be selected? Nope. By default NO days should be select
Should the current day be selected by default? Nope
Should it be possible to de-select all days of the week, and if so: Yes
When no days of the week are selected, is the current day assumed to be selected? No, but validation should catch that at least one is selected if the dropdown is set to weekly.

![image](https://user-images.githubusercontent.com/535300/62316576-ab8a6a00-b44c-11e9-9337-7d9ce2cdc5ad.png)
