### ISSUE TITLE
Must click undo twice on new Boundary Timer Event

### ISSUE THREAD

**Issue by lisa-fehr** [ProcessMaker/modeler#509]
**How to reproduce bug**

* Place a Task on the screen
* Drag an Intermediate Timer Event onto the Task until it attaches as a Boundary Timer Event
* Click Undo twice

**Expected Behaviour**
Should only have to click Undo once

**Actual Behaviour**
Need to click Undo twice to remove the timer. Redo is also able to be clicked twice.

https://www.dropbox.com/s/arap0n11h6askv8/UndoBoundaryTimerError.mov

**Comment by lisa-fehr** [comment]
Note: this issue seems to be fixed in JointJs 3

**Comment by JCook21** [comment]
This is no longer reproducible. Closing.
