### ISSUE TITLE
Boundary Event Implementation Discussion

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#520]
All boundary events share these key features: 

- [x] Drag on to task elements (task, manual task, script task, connector and call activity)
- [x] Reposition around the border of the element with 3 connection points per side (for a total of 12)
- [x] Crown for deleting boundary event
- [x] Crown for add flow elements
- [x] Support for solid and dashed borders
- [x] Inspector configuration
- [x] Icon
- [x] Name
- [x] Can be moved between connection points 
- [x] Can be moved between other tasks

**Comment by velkymx** [comment]
This is a good overview of boundary events in general:

https://www.youtube.com/watch?v=JKl6ar8APfY

**Comment by caleeli** [comment]
Please also take in count to move the boundary event name so we could put it in a proper place in the diagram:

![image](https://user-images.githubusercontent.com/8028650/63167460-63984500-bfff-11e9-8b8d-9c84c61d4563.png)

**Comment by tuantruong625** [comment]
Mocks of the grouped controls

![grouped-controls](https://user-images.githubusercontent.com/26545455/63178749-ad415980-c018-11e9-905b-160eb3d72ce0.png)

**Expanded**
![grouped-controls-expanded](https://user-images.githubusercontent.com/26545455/63178750-ad415980-c018-11e9-8933-acca1d9b12ff.png)

**Comment by JCook21** [comment]
I think this is now closed given the work we've completed on boundary timer events.
