### ISSUE TITLE
Async rendering: Red error border disappears after undo

### ISSUE THREAD

**Issue by chipit24** [ProcessMaker/modeler#538]
This is a partial regression of https://github.com/ProcessMaker/modeler/issues/412.

**Steps to reproduce:**
1. Enable auto validation:
   <img width="133" alt="Screen Shot 2019-08-20 at 4 55 27 PM" src="https://user-images.githubusercontent.com/7561061/63383710-54045d80-c36b-11e9-96e5-07e48f9bae84.png">
2. Modify the start event (drag it to a new position or change its name or ID).
3. Press Undo.

**Current behaviour:**
* Although there is a validation error with the start event, the red border around the start event has disappeared and doesn't re-appear.

**Expected behaviour:**
* As there is a validation error for the start event, the red border around it should remain visible:
  <img width="94" alt="Screen Shot 2019-08-20 at 4 58 14 PM" src="https://user-images.githubusercontent.com/7561061/63383900-b78e8b00-c36b-11e9-8054-2ab2b3b0248b.png">

**Note:**
 * Fixing this bug should fix the failing test for "updates validation after undo/redo" without causing further tests to fail.

**Comment by lisa-fehr** [comment]
Resolved in #540
