### ISSUE TITLE
Undo/redo on Boundary Timer Event removed from Task leaves a copy of Intermediate Timer Event

### ISSUE THREAD

**Issue by lisa-fehr** [ProcessMaker/modeler#545]
**Steps to reproduce:**
1. Drag a Task onto the screen
2. Drag an Intermediate Timer onto the Task to attach it as a Boundary Timer
3. Drag the Boundary Timer off the Task until it is an Intermediate Timer again
3. Click Undo
<img width="320" alt="Screen Shot 2019-08-21 at 2 19 30 PM" src="https://user-images.githubusercontent.com/6653340/63457279-b79b9300-c41e-11e9-925d-8d5a7991e9d0.png">

https://www.dropbox.com/s/5g57ek4xjuf81x2/timer-copy-on-undo.mov?dl=0

**Current behaviour:**
* After clicking Undo, an Intermediate Timer Event remains on the screen. While the Boundary Timer Event is back on the Task

**Expected behaviour:**
* The Intermediate Timer Event should disappear when becoming a Boundary Timer again

**Note**
When reproducing this scenario on develop, Undo doesn't work at all

**Comment by chipit24** [comment]
Closing this issue as the implementation has changed.
