### ISSUE TITLE
sourceAnchor of undefined error when dragging Boundary Event off Task

### ISSUE THREAD

**Issue by lisa-fehr** [ProcessMaker/modeler#554]
Boundary Timer Event behavior is changing, so this might not be a priority. Noting the issue.

**Steps to reproduce:**
1. Attach an Intermediate Timer to a Task
2. Drag an End Event onto the screen
3. Add a Sequence Flow from the Boundary Timer to the End Event<img width="357" alt="Screen Shot 2019-08-22 at 4 29 08 PM" src="https://user-images.githubusercontent.com/6653340/63547382-09fdb200-c4fa-11e9-8def-45fba34799af.png">
4. Drag the Boundary Timer off the Task until it becomes an Intermediate Timer again<img width="313" alt="Screen Shot 2019-08-22 at 4 29 18 PM" src="https://user-images.githubusercontent.com/6653340/63547392-1255ed00-c4fa-11e9-8623-f2b743f5640e.png">

https://www.dropbox.com/s/sjzbk04ur70kqmm/sourceAnchorError.mov?dl=0

**Current behaviour:**
There is a console error of "Uncaught TypeError: Cannot read property 'sourceAnchor' of undefined". The Intermediate Timer Event doesn't have a Sequence Flow to the End Event anymore.

**Expected behaviour:**
There should not be a console error. Intermediate Timer Event does not need to retain the Sequence Flow, but could be a nice to have.

**Comment by chipit24** [comment]
The implementation has changed to no longer allow dragging boundary events off of a task onto the paper. This issue is no longer relevant.
