### ISSUE TITLE
Display error message if XML parsing fails

### ISSUE THREAD

**Issue by JCook21** [ProcessMaker/modeler#561]
Currently we silently swallow errors on failing to parse BPMN XML documents. We should display some sort of error to the user.

**Comment by lisa-fehr** [comment]
As a note:

Since these warnings are grouped with validation, they don't automatically display unless validation is toggled on.

They used to be toast messages.

**Comment by chipit24** [comment]
Closing, as there's no motivations for this enhancement (no reported issues of users uploading invalid XML processes that results in a blank page / ignored errors), and this issue is not currently a priority.
