### ISSUE TITLE
Fix Intermediate Catch Event: Sets default values when switching between types

### ISSUE THREAD

**Issue by JCook21** [ProcessMaker/modeler#568]
This test is failing in the `feature/564-update-processmaker-dependencies` branch. Related to #564.

**Comment by lisa-fehr** [comment]
New date picker was passing DateTime as the value. But it expected something else with a search function on it.
![Screen_Shot_2019-08-28_at_5_03_23_PM](https://user-images.githubusercontent.com/6653340/63948886-7c651980-ca47-11e9-9030-18f23746ccf5.png)
