### ISSUE TITLE
Fix Start Timer Event: Update properties on Start Timer Event

### ISSUE THREAD

**Issue by JCook21** [ProcessMaker/modeler#571]
This test is failing in the feature/564-update-processmaker-dependencies branch. Related to #564.

**Comment by caleeli** [comment]
Can not change the start timer event configuration.
 
[TimerStartEventNotSavingConfig.mov.zip](https://github.com/ProcessMaker/modeler/files/3560601/TimerStartEventNotSavingConfig.mov.zip)

**Comment by JCook21** [comment]
@caleeli can you please clarify that comment, I'm not sure what you're saying or suggesting.

**Comment by chipit24** [comment]
`feature/564-update-processmaker-dependencies` (https://github.com/ProcessMaker/modeler/pull/574) has been merged, and the failing start timer event test is currently passing on `develop`. So I'll close this issue.

@JCook21 The video @caleeli posted demonstrates a new problem with start timer events that I'll document in a new issue. It appears that the start timer event config isn't correctly being saved. It seems the config only works correctly when the periodicity is set to "week".

@caleeli please add more details when reporting problems. Not everyone looking at the video or codebase will have a clear understanding of what you mean. And even then, when you don't explicitly define your problem, we're left filling in the gaps and that may lead to incorrect assumptions.
