### ISSUE TITLE
Imported BPM file makes control icons look larger than expected

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#575]
![image](https://user-images.githubusercontent.com/535300/63861857-806a3c00-c960-11e9-99ac-6be5ec26e24b.png)

BPMN test

[CP.01.00.01 Check for connected clients.bpmn.txt](https://github.com/ProcessMaker/modeler/files/3551242/CP.01.00.01.Check.for.connected.clients.bpmn.txt)

**Comment by chipit24** [comment]
Re: my previous comment: The current behaviour will be left as-is. Closing as there is no other work to do for this issue.
