### ISSUE TITLE
Need a way for registered extensions to get the highlightedNode cleanly

### ISSUE THREAD

**Issue by nolanpro** [ProcessMaker/modeler#584]
Lots are places are using $parent.$parent.$parent etc and [hacky helpers](https://github.com/ProcessMaker/connector-send-email/blob/5cb4ffb1eaa9d645719d4ad741e8ff886eb73a91/resources/js/helper.js#L1-L23) that iterate over the tree to find it. Highlighted node should be made available to extensions through some kind of listener

**Comment by chipit24** [comment]
I'm going to fill in some gaps to give this issue more context. Please correct me if this is wrong.

Extensions are registered in the modeler using the `registerInspectorExtension` method that is passed to the `modeler-init` event listener. This is documented in the README at https://github.com/ProcessMaker/modeler#modeler-init.

The `registerInspectorExtension` method accepts two arguments, the node you want to add the extension to, and the extension config. The extension config specifies what controls appear in the inspector panel when you highlight that node in the modeler.

Now, this inspector config is loaded by the screen builder's vue-form-renderer component, which is itself a child of the `Modeler.vue` component. The `Modeler.vue` component has a reference to `highlightedNode`. So from this, it can be seen that any inspector component that wants to have access to `highlightedNode` would currently need to climb up this stack and reach into `Modeler.vue` to grab that reference.

Chaining calls to [`$parent`](https://vuejs.org/v2/api/#vm-parent) may work to grab that reference.
_____

Now that that's out of the way, let's clarify the issue with `$parent`:

Using `$parent` isn't "clean" for two reason:
1. It's fragile. Anytime a component in the stack changes–either an extra component layer is added or removed–calls to `$parent` will have to be added/removed accordingly.
2. There's no clear indication as to what `$parent.$parent` actually refers to. `$parent` isn't descriptive, and to get a clear understanding of this dependency, someone would have to manually drill into each parent to get a complete picture of what's going on.

**Comment by chipit24** [comment]
Since `highlightedNode` is specified in a VueX store, I think it would be best to ensure that store is correctly set up and registered with the Vue instance, then it can be accessed in any component using `this.$store.getters.highlightedNode`.

Emitting an event when `highlightedNode` changes may not work as expected, as highlighting a node is what renders a new inspector config. So the event which triggers the highlighted node to change would already have been called before the code which expects to hook into that even is executed.

**Comment by JCook21** [comment]
I'm going to close this issue as there hasn't been any updates on it since the end of August. Please reopen if this is still an issue.
