### ISSUE TITLE
Validate drop target for Boundary Event

### ISSUE THREAD

**Issue by tuantruong625** [ProcessMaker/modeler#589]
Only allow task elements as valid drop targets.

Valid Targets:
- Task
- Script Task
- Manual Task
- Call Activity
- Connectors ex. Twitter Connector Task, Sales Force 

For invalid targets, element should highlight red and boundary event should not appear if dropped. 

Reference #581

**Acceptance Criteria**
- If a boundary event is dropped onto a valid target then it will render on the paper.
- ~The shape being hovered over by the boundary event will turn red if it is of an invalid type.~ Broken out into separate issue: https://github.com/ProcessMaker/modeler/issues/607.
- When you drag a boundary event from controls and try to drop it on an invalid element the event will not render.

**Comment by JCook21** [comment]
Merged in #608
