### ISSUE TITLE
Allow boundary events to snap to edges of tasks

### ISSUE THREAD

**Issue by JCook21** [ProcessMaker/modeler#593]
As a user, when I drop a boundary event onto a task it should snap to the nearest connection point on the closest edge.

**Acceptance Criteria**
- Each task edge should have 3 connection points
- When a boundary event is released over a task it snaps to the closest connection point
- Connection points are distributed on the left, right and middle of each side
- Connection points do not overlap at corners
- Connection points are evenly distributed on each side
- Boundary events can be moved between connection points

**Comment by lisa-fehr** [comment]
Completed in #605  and #612
