### ISSUE TITLE
Strange line rendering between close elements

### ISSUE THREAD

**Issue by ryancooley** [ProcessMaker/modeler#594]
Per @tdondich, lines on elements that are close together are incorrectly rendered:
![Screen Shot 2019-09-03 at 2 36 20 PM](https://user-images.githubusercontent.com/867714/64210506-529d5f80-ce58-11e9-9c9f-225e30804bf7.png)

When moved further apart, the lines straighten out:
![Screen Shot 2019-09-03 at 2 36 32 PM](https://user-images.githubusercontent.com/867714/64210534-68128980-ce58-11e9-8588-1b0320760293.png)

The lines should remain straight as much as possible.

**Comment by JCook21** [comment]
@ryancooley could you add some more information for us:

- Is there a BPMN file import that reproduces this issue?
- Is this specific to tasks joining to an exclusive gateway or any elements?
- Can you please post complete reproduction steps. This will save us a huge amount of time and avoid uncertainty when trying to reproduce this issue.

**Comment by ryancooley** [comment]
Hi Jeremy. This came out of our fire drill issue yesterday. We noticed this with the BPMN file the stakeholders were trying to import.

1. Here is the specific BPMN file in question: 
[adonis.bpmn.zip](https://github.com/ProcessMaker/modeler/files/3575890/adonis.bpmn.zip)

2. I don't know, we haven't had time to test that extensively.

3. Import and open the process in the designer.

**Comment by chipit24** [comment]
Closing, as this is the same issue as https://github.com/ProcessMaker/modeler/issues/685.
