### ISSUE TITLE
Fix node name rendering

### ISSUE THREAD

**Issue by sanjacornelius** [ProcessMaker/modeler#595]
Fix the rendering of node names within the validation panel to display on top rather than to the side. ![Screen Shot 2019-09-03 at 2 36 40 PM](https://user-images.githubusercontent.com/52755494/64210562-7cef1d00-ce58-11e9-9519-be35acd2a722.png)

**Comment by lisa-fehr** [comment]
Closing. Node ids were moved below the message in #831
