### ISSUE TITLE
Wacky Flow Arrows with imported .bpmn file

### ISSUE THREAD

**Issue by PMQABen** [ProcessMaker/modeler#598]
[adonis.bpmn.txt](https://github.com/ProcessMaker/modeler/files/3571743/adonis.bpmn.txt)
(remove the .txt when importing)

**How the Process should look (opened via Camunda Modeler)**
![image](https://user-images.githubusercontent.com/28575916/64211017-abb9c300-ce59-11e9-847b-684048250b01.png)

**How the Process looks when imported into PM4 Modeler:**
![image](https://user-images.githubusercontent.com/28575916/64211239-5c27c700-ce5a-11e9-8821-83cf04d9893c.png)

**Flow arrows and text annotation lines are taking odd paths in multiple areas.**
![image](https://user-images.githubusercontent.com/28575916/64211267-79f52c00-ce5a-11e9-84a4-2ca1bac68f24.png)

**Comment by chipit24** [comment]
Closing, as this is the same issue as https://github.com/ProcessMaker/modeler/issues/685.
