### ISSUE TITLE
Fix Test - Intermediate Catch Event: Sets default values when switching between types 

### ISSUE THREAD

**Issue by tuantruong625** [ProcessMaker/modeler#638]
Assertion on XML does not match with the expected XML.

References #637 

PR for fix(https://github.com/ProcessMaker/vue-form-elements/pull/89)

**How to test**
- npm link to vue-form-elements branch to modeler

**Expected**
Intermediate Catch Event: Sets default values when switching between types `passes.`

**Comment by chipit24** [comment]
@tuantruong625 This doesn't appear to be fixed by the linked PR. The linked PR does appear to fix the failing test for _Update properties on Start Timer Event for "week" periodicity_.

**Comment by chipit24** [comment]
Expected: `<bpmn:timeDate>1970-01-01T00:00:00.000Z</bpmn:timeDate>`
Received: `<bpmn:timeDate>1970-01-01T00:00:00Z</bpmn:timeDate>`

Looks like we can just truncate the end (`.000`); rest of the date is as expected.
