### ISSUE TITLE
Add Error Boundary Event

### ISSUE THREAD

**Issue by chipit24** [ProcessMaker/modeler#659]
The error boundary event should look like this:
<img width="143" alt="Screen Shot 2019-09-19 at 2 26 07 PM" src="https://user-images.githubusercontent.com/7561061/65270595-824f9700-dae9-11e9-9ce5-493d656997d7.png">

And produce the following BPMN XML:
```xml
<boundaryEvent id="some_id" attachedToRef="some_task">
  <errorEventDefinition />
</boundaryEvent>
```

Tasks:
 - [ ] Create a separate boundary event component extending the base boundary event.
    * Ensure the correct icon is loaded: `/src/assets/boundary-error-event-icon.svg`.
    * Ensure the BPMN XML only includes `errorEventDefinition` without a `cancelActivity` attribute.
    * Overwrite default config properties with any boundary event specific config, that we know of at this time.
    * Ensure the error boundary event is available in the list of nodes and is correctly parsed on upload or undo/redo (add to `defaultNodes.js`).
    * Out of scope for now: errorRef property of the event.
    * Automated test:
        * Drag event type onto valid drop target.
        * Download XML.
        * Assert that the XML contains the snippet required from the BPMN docs.

**Comment by velkymx** [comment]
[PM4-ErrorBoundaryEvent-230919-2108.pdf](https://github.com/ProcessMaker/modeler/files/3648032/PM4-ErrorBoundaryEvent-230919-2108.pdf)
