### ISSUE TITLE
Add Error End Event

### ISSUE THREAD

**Issue by chipit24** [ProcessMaker/modeler#661]
The Error End Event should look like this:
<img width="73" alt="Screen Shot 2019-09-19 at 2 54 33 PM" src="https://user-images.githubusercontent.com/7561061/65272627-6b12a880-daed-11e9-8368-16cdc78767d1.png">

And produce the following BPMN XML:
```xml
<endEvent id="some_endEvent">
  <errorEventDefinition />
</endEvent>
```

Tasks:
 - [ ] Create a new end event Vue component.
 - [ ] Create a new config for the end event.
   * The config should reference the correct icon, and include `errorEventDefinition`.
 - [ ] Ensure the component appears in the controls list and is parsed during upload and undo/redo (add it to `defaultNodes.js`).

**Comment by velkymx** [comment]
[PM4-ErrorBoundaryEvent-230919-2108.pdf](https://github.com/ProcessMaker/modeler/files/3648030/PM4-ErrorBoundaryEvent-230919-2108.pdf)

**Comment by chipit24** [comment]
This was duplicated in https://github.com/ProcessMaker/modeler/issues/755, and has now been implemented.
