### ISSUE TITLE
SPIKE: investigate effort required for multi-select of elements in a process.

### ISSUE THREAD

**Issue by JCook21** [ProcessMaker/modeler#669]
Selected tasks should be able to be moved together. Sequences outside that go outside of the selected group should update as the group is moved.

**Comment by lisa-fehr** [comment]
Sounds like we need a menu item for a lasso.

We can render a rectangle on mousedown, resize it on mousemove and then capture its dimensions. Pass the dimensions to findModelsInArea, embed/highlight those elements and then remove the rectangle.

Camunda deselects when clicking whitespace on the paper, or when deselecting the lasso.

Since dragging on the paper currently moves the view, we may need some time to confirm everything behaves as expected when the lasso tool is introduced. 

@JCook21 @chipit24 Would this be up to a full sprint estimate?

**Comment by JCook21** [comment]
@lisa-fehr I think this sounds fair. One question before I think we can break this down: is it possible to disable moving the view on the paper when a 'lasso' tool is selected? If not this whole thing may be impossible.

**Comment by lisa-fehr** [comment]
If we can stop this code from firing when using the lasso, I believe we can disable dragging the paper temporarily.
```php
Modeler.vue ~line 894

this.paper.on('blank:pointerdown', (event, x, y) => {
      const scale = this.paper.scale();
      this.canvasDragPosition = { x: x * scale.sx, y: y * scale.sy };
      this.isGrabbing = true;
});
this.paper.on('cell:pointerup blank:pointerup', () => {
      this.canvasDragPosition = null;
      this.isGrabbing = false;
});

this.$el.addEventListener('mousemove', event => {
      if (this.canvasDragPosition) {
        this.paper.translate(
          event.offsetX - this.canvasDragPosition.x,
          event.offsetY - this.canvasDragPosition.y,
        );
      }
});
```

**Comment by JCook21** [comment]
@chipit24 is it possible to remove and re-register these events?

**Comment by chipit24** [comment]
@JCook21 Yes, it's possible.

**Comment by chipit24** [comment]
The following tasks will need to be completed to implement this feature:
 1. Add a lasso/multiselect button to the toolbar
 2. When the button is pressed:
    1. Disable dragging of the paper
    2. When the paper is now "dragged", a selection box should be drawn instead
       1.  The selection box can be created by adding a rectangle on mousedown and resizing the rectangle on mousemove
       2. [`findModelsInArea`](https://resources.jointjs.com/docs/jointjs/v3.0/joint.html#dia.Graph.prototype.findModelsInArea) can be used on mouseup to capture all the nodes in the rectangle, highlight them, embed them into a single shape to enable dragging them, and then removing the selection rectangle
    3. Re-enable dragging of the paper when the button is pressed again, when another individual element is highlighted, or when the blank grid is clicked

1 can be added to a base branch, and then 2 can be split up into individual tasks to be merged in. I don't think we need a full sprint week to implement this. I would give it 3 days.

**Comment by JCook21** [comment]
@chipit24 sounds good but remember to factor some time in for 'unknown unknowns'. Given the length of our sprints I think a week to deliver this is safe (effectively our sprint is 4 days so...)

**Comment by lisa-fehr** [comment]
Next consideration: The pro version of a fontawesome lasso isn't great.
![Screen Shot 2019-09-25 at 1 37 36 PM](https://user-images.githubusercontent.com/6653340/65625356-a7d11a80-df99-11e9-9afa-b125e8256d16.png)

Simplest placement would be the undo/redo tool area? It might start squishing the mini-map if the map gets moved into the toolbar area. I tested with a vector square icon.

![newIconPlacement](https://user-images.githubusercontent.com/6653340/65625301-8a03b580-df99-11e9-825a-eb3017c1c4a3.png)

**Comment by JCook21** [comment]
@lisa-fehr I think we can cross that bridge if/when we need to implement this feature. :)

**Comment by JCook21** [comment]
Closing this as the spike is complete for now.
