### ISSUE TITLE
Deleting a Start Event causes a process to fail validation

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#674]
# Bug report issue
## Description
I created an additional Start Event to test a separate Web Entry. After testing, I deleted my Start Event. Now the process shows a ⚠️ warning sign and prevents execution. The warning reads that the deleted element is not found. Only way to re-enable the process is to add a new Start Event and rename it as the expected deleted one.
## Reproduction steps
To replicate:

1. Open this process: https://staging-pm4.processmaker.net/modeler/52
1. Notice the third Start Event called node_9 half way through the process:
![image](https://user-images.githubusercontent.com/535300/65516122-445dc480-de95-11e9-9eeb-93b420f42fe0.png)
1. Delete it. Save. Notice the error in the process list.
![image](https://user-images.githubusercontent.com/535300/65516142-4f185980-de95-11e9-8dfd-4c502a360421.png)
1. Reopen. Notice the warning. Element "node_9" was not found that is the deleted Start Event. 
![image](https://user-images.githubusercontent.com/535300/65516171-5d667580-de95-11e9-952b-c103d4ca46f3.png)
1. Add a new Start Event, rename the identifier to node_9. Process will save and warning will go away. Process will be functional.
![image](https://user-images.githubusercontent.com/535300/65516193-69eace00-de95-11e9-9e35-31e5f625e1b3.png)

## Expected Behavior
Once an element is deleted, the data for it should no longer be referenced

## Other information
Tried to test if the same happens with an End Event. Deleted the last end event (there is another end event elsewhere). Routed the process back into another component instead. Now I also get a warning in the list, and upon reopening, Im getting this weird error: the sequence that used to route back into another element is now hanging out there:

![image](https://user-images.githubusercontent.com/535300/65516329-b0402d00-de95-11e9-81d2-200e1cee6586.png)

Notice also the Schema Validation error: *Schema Validation
//www.omg.org/spec/BPMN/20100524/DI}BPMNShape', attribute 'id'false 'node_1_di' is not a valid value of the atomic type 'xsfalseID'.*

And if I try to delete the weird sequence arrow that connects to nowhere, I get this error: Cannot read property $descriptor of undefined

![image](https://user-images.githubusercontent.com/535300/65516343-b930fe80-de95-11e9-9f26-f1042a23b0d0.png)

**Comment by velkymx** [comment]
Process export: 
[-_h_e-_student_change_of_major_request.json.txt](https://github.com/ProcessMaker/modeler/files/3647427/-_h_e-_student_change_of_major_request.json.txt)

**Comment by JCook21** [comment]
@velkymx there seem to be a number of issues with this process. To start with, the Camunda docs state that it's only valid to have a [single 'unnamed' start event](https://docs.camunda.org/manual/7.11/reference/bpmn20/events/start-events/) but this process has 3. The bigger issue with this is that it's impossible to debug this process in it's current state as it is already corrupted and we cannot see the original issue. Can you send us an export of the process as it was before any changes were made? Without that I'm not sure how we can diagnose this.

**Comment by chipit24** [comment]
Here is the XML from the attached process: https://www.dropbox.com/s/9gf5r7eugwnp1a6/student_change_of_major_request.xml?dl=0.

There are a few errors when I upload this process in the standalone modeler. I didn't notice anything strange with the definition of the node_9 start event, however, I was able to reproduce a bug that may be the cause of the problem: https://github.com/ProcessMaker/modeler/issues/676.

**Comment by JCook21** [comment]
@velkymx can you see if #676 has fixed this issue?

**Comment by velkymx** [comment]
I think we're good on this one. Will reopen if the issue comes up again.
