### ISSUE TITLE
Only allow one error boundary event per task

### ISSUE THREAD

**Issue by chipit24** [ProcessMaker/modeler#679]
Has to be done after https://github.com/ProcessMaker/modeler/issues/659.

As per the PRD, [PM4-ErrorBoundaryEvent-230919-2108.pdf](https://github.com/ProcessMaker/modeler/files/3648032/PM4-ErrorBoundaryEvent-230919-2108.pdf), only one error boundary event can exist per task.

**Question:**
Should the validation around dragging an error boundary event on a task which already has one be the same as dragging it over any other invalid target? I.e. The cursor will be a "no-drop" cursor, and the boundary event won't render when dropped.

**Comment by JCook21** [comment]
Work on this is completed and merged.
