### ISSUE TITLE
Switching between like nodes does not fully reload inspector

### ISSUE THREAD

**Issue by nolanpro** [ProcessMaker/modeler#683]
Switching between 2 tasks without clicking on the background first does not load all the correct inspector settings. Some settings, like node ID, change correctly. But others, like the selected users or groups, and any settings injected by a package, do not change.
![Kapture 2019-09-24 at 13 52 27](https://user-images.githubusercontent.com/2546850/65549961-7130cc80-ded3-11e9-9acf-cdd43836923f.gif)

**Comment by lisa-fehr** [comment]
Closing. This doesn't appear to be an issue anymore. 

Processmaker with Screen Builder v. 0.20.6

https://www.dropbox.com/s/4j9ma01k2zsycdz/updatingTaskAssignment.mov?dl=0
