### ISSUE TITLE
Looping Lines

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#685]
# Bug report issue
## Description
When dragging two elements close together the straight element flow flips around and is lost. 
![image](https://user-images.githubusercontent.com/535300/65614210-17c8ac00-df6c-11e9-8b44-4ad6994a1679.png)

Video: https://www.dropbox.com/s/9x8lkwk1eze361h/loopingflow.mov?dl=0
## Reproduction steps
Take two tasks and connect them with an element flow. Then drag them close together.
## Expected behaviour
The line should stay straight.

**Comment by chipit24** [comment]
Looks like there was some discussion around this a few months back, in https://github.com/ProcessMaker/modeler/issues/183#issuecomment-459830229:

> There is a bit of tweaking that can be done with jointjs, but there will always be edge cases when sequence flows don't look quite right. E.g. I updated the router to help prevent overlapping, but it still falls apart when elements are very close:
>
> A complete solution may require setting up a custom router, anchors, and connectPoints, as well as precisely defining what the problem is (how flows should appear in all cases). This requires more discussion.

I think it's clear that unless we create a custom router, sequence flows will not behave how everyone might expect them to. However, to accomplish this, we need to know exactly how sequence flows should behave in all situations, otherwise a custom router might fix this one edge case while introducing issues in other cases.

**Comment by chipit24** [comment]
So, we can fix this edge case by switching from JointJS's `orthogonal` router to its `manhattan` router, but the `manhattan` router has issues with looping and making 90 degree joints too close to the connecting elements.

A custom router can solve these issues as we would specify how it would behave in all cases. But, we'll need to answer questions like:
 * How should two elements connect when they overlap on their connecting edges?
 * Should sequence flows avoid any obstacles?
 * Where should sequence flows make their "turns"? Should there only be one 90 degree turn when connecting tow elements?

A custom router is also something we'd have to plan for next sprint, as it could take a few days to fully implement and test.

**Comment by JCook21** [comment]
@velkymx can you have a look at Rob's comments and let us know how to proceed? I'm wondering if we can treat this as an enhancement and schedule accordingly. I certainly don't think this is something that should be rushed as there is the possibility of introducing other rendering issues along the way.

**Comment by chipit24** [comment]
Closing as this is the same issue as https://github.com/ProcessMaker/modeler/issues/685.
