### ISSUE TITLE
Make the inspector and control columns the same width

### ISSUE THREAD

**Issue by lisa-fehr** [ProcessMaker/modeler#693]
The solution for #487 doesn't work well with wider columns.

Might have to reduce the size of the mini-map. Or show the mini-map below the toolbar again and make the toolbar white, so people don't try to interact with the graph through it.

![Screen Shot 2019-09-25 at 5 06 25 PM](https://user-images.githubusercontent.com/6653340/65887488-fd2b7400-e36b-11e9-9ab1-38a0affcbed2.png)

**Comment by lisa-fehr** [comment]
Merged in #710

**Comment by velkymx** [comment]
The modeler is not reflecting this change in the latest builds. 

![image](https://user-images.githubusercontent.com/535300/67419235-3331d180-f581-11e9-8b5a-9213e0d6a88c.png)

**Comment by lisa-fehr** [comment]
@velkymx Is that correct? Event the mini-map is in an old location.

I'm trying to reproduce, but not having success.

**Comment by chipit24** [comment]
I'm with @lisa-fehr. Looks like a much older version of modeler from the screenshot. I tested it on the latest processmaker `develop` branch (with nothing linked in) and it looks good.

**Comment by velkymx** [comment]
Looks like an update didn't happen. Closing
