### ISSUE TITLE
Highlight Required fields in the same way as screen builder in the inspector

### ISSUE THREAD

**Issue by chipit24** [ProcessMaker/modeler#708]

**Comment by chipit24** [comment]
It seems this is already set up, at least on some inspector inputs:
<img width="254" alt="Screen Shot 2019-09-30 at 11 11 01 AM" src="https://user-images.githubusercontent.com/7561061/65891986-809c9380-e373-11e9-8bb3-300fedfe05d7.png">

The change is as simple as adding `validation: 'required'` to the config. What other inputs would require this?

**Comment by chipit24** [comment]
@velkymx

**Comment by velkymx** [comment]
This is ok. I'll work on a master inspector doc with required fields
