### ISSUE TITLE
Advanced Accordion always last

### ISSUE THREAD

**Issue by chipit24** [ProcessMaker/modeler#709]
The advanced accordion should always be the last accordion in the inspector panel:

<img width="284" alt="Screen Shot 2019-09-30 at 11 18 43 AM" src="https://user-images.githubusercontent.com/7561061/65892326-146e5f80-e374-11e9-8cb0-b4f8bac53849.png">

In some cases, the advanced accordion does not appear last, like for the task component:
<img width="291" alt="Screen Shot 2019-09-30 at 11 19 20 AM" src="https://user-images.githubusercontent.com/7561061/65892392-37990f00-e374-11e9-8a2c-0fdab0704184.png">

This occurs because calls to `registerInspectorExtension` does not maintain the order of the inspector accordions.

**Comment by velkymx** [comment]
In the Intermediate Timer Event element, the "Advanced" accordion is in the wrong place. In all the other elements, the "Advanced" accordion is the second from the top (after "Configuration"). In the Intermediate Timer Event element, it is the third (after "Timing Control").
