### ISSUE TITLE
Add crown as bubble to the top right.

### ISSUE THREAD

**Issue by lisa-fehr** [ProcessMaker/modeler#725]
Investigate. Do if simple enough.

Move it to a row that appears in a bubble to the top right of the shape.

You could click it and it expands to show all available crown buttons.

Can a shadowed background be added to the crown controls.

Bonus: animated

**Comment by lisa-fehr** [comment]
What it should look like needs to be approved. One possibility, is making the crown bubble look similar to the expand/collapse on the mini-map.
![Screen Shot 2019-10-04 at 4 15 36 PM](https://user-images.githubusercontent.com/6653340/66238248-1febbe80-e6c5-11e9-939d-720bcbd9d0fa.png)


There are a couple ways to add a dropshadow:
https://resources.jointjs.com/docs/jointjs/v3.0/joint.html#dia.Paper.prototype.defineFilter
https://resources.jointjs.com/tutorial/filters-gradients
But using css, like the min-map, might be best.

Transition has some animation options. It might be able to resize/expand or fade in - with delay or duration:
https://resources.jointjs.com/docs/jointjs/v3.0/joint.html#dia.Element.prototype.transition
Css transition animations might also be an option. With potential complexity, this might need to be an enhancement later. 

Crown control buttons aren't currently inside another shape, so some re-coding will need to be done. The mini-map bubble is stationary, so it can't be used entirely as is. The basics should be implemented in one sprint. Two sprints max, to work out any kinks.

Any thoughts? @JCook21 @tuantruong625 @chipit24

**Comment by JCook21** [comment]
Looks great @lisa-fehr! Thanks.
