### ISSUE TITLE
User Task Icon Missing

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#730]
The user task should have a little person icon in the corner (like the manual task) 

![image](https://user-images.githubusercontent.com/535300/66435366-87618100-e9d9-11e9-9fd5-546c9e5d45d5.png)

**Comment by lisa-fehr** [comment]
@velkymx Might need the person svg. It doesn't appear to be in the assets folder.

**Comment by chipit24** [comment]
@velkymx I don't see a user task anywhere in modeler or processmaker. Was it removed? Is this still an issue?

**Comment by velkymx** [comment]
This is the default type of task. This is the icon
https://fontawesome.com/icons/user?style=solid

**Comment by chipit24** [comment]
The only place I see user task mentioned is in `modeler/src/components/nodes/task/index.js`; if the BPMN XML contains `bpmn:UserTask` then it will be converted to a regular task. It seems the modeler currently does not support user tasks.

It seems the user task needs to be implemented; in which case this is an enhancement, not a bug, and the user task icon isn't missing, the entire user task is missing and has to be implemented. Let's discuss this during standup tomorrow.

User task documentation: https://docs.camunda.org/manual/7.8/reference/bpmn20/tasks/user-task.

**Comment by chipit24** [comment]
Task is to add the user icon to the default task component.
