### ISSUE TITLE
Processes Being Corrupted 

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#743]
The process is broken when it's being designed, I cannot found the exact steps as this reproduces randomly, however it could be related with intermediate web entry and modifications in the flows. The process is corrupted and cannot save anymore.

You can see the attached video and corrupted process.

https://www.dropbox.com/s/4r97csjl0ot87eq/webentry_modeler_2-2019-09-26_09.45.33.mp4?dl=0

**Comment by chipit24** [comment]
Big might have been introduced by https://github.com/ProcessMaker/screen-builder/issues/351.

**Comment by chipit24** [comment]
Was able to reproduce the issue locally. Rolled back the changes in https://github.com/ProcessMaker/screen-builder/pull/413 and the issue was resolved.
