### ISSUE TITLE
SequenceFlow is a duplicate

### ISSUE THREAD

**Issue by lisa-fehr** [ProcessMaker/modeler#780]
# Bug report issue
## Description
When auto validating a diagram while creating (or toggling it twice after an import), it will display that the sequence flows are duplicated when they are not.
## Reproduction steps
1 ) Turn on Auto Validation
2) Add an End Event
3) Add a Task
4) Connect the Start Event to the Task
5) Connect the Task to the End Event
## Expected behaviour
There should be no problems with the Sequence Flows
## Actual behaviour
It shows that the Sequence Flows are duplicated in the problems box
## Software used
Latest Chrome. Modeler v. 0.17.5
## Other information
<img width="860" alt="Screen Shot 2019-11-01 at 3 52 54 PM" src="https://user-images.githubusercontent.com/6653340/68052852-f5d7ed00-fcc0-11e9-8fb7-04ee886643c3.png">

**Comment by lisa-fehr** [comment]
@JCook21 I found the commit where this bug is introduced. I'm assuming it is due to an upgraded package (or many upgraded packages). https://github.com/ProcessMaker/modeler/commit/4e61fb9ae8234580aca21d0342c2323251d5cd8a

**Comment by chipit24** [comment]
The problem appears to be with the `bpmnlint` package. A temporary fix for now would be to disable the rule in the `.bpmnlintrc` file:
```
"no-duplicate-sequence-flows": "off"
```
