### ISSUE TITLE
Add ability to collapse and expand left (element controls) sidebar

### ISSUE THREAD

**Issue by chipit24** [ProcessMaker/modeler#781]
Add a button to collapse the element controls sidebar.

![Image from iOS](https://user-images.githubusercontent.com/7561061/68147794-d9c68c80-ff08-11e9-8c3c-e7747e350c6b.jpg)

Questions:
* How should the collapse of the panel be initiated? Should there be a button to the right of the panel?
* Should the filter input be hidden or disabled when the sidebar is collapsed?
* Should it be collapsed by default?

Acceptance criteria:
* The element controls panel will remain expanded by default (we can assume for now to get started).
* It should still be possible to drag elements onto the canvas with the panel collapsed.
* You should still be able to drop elements onto the canvas in the extra space produced by the collapsed panel. The grid in this area should also still be visible and interactive.
* You should still be able to scroll the list of controls if it overflows the bottom of the view.
* Tooltips should still appear when hovering over a control.

Note: In the screenshot the collapsed panel was implemented by reducing the width of the panel container.

**Comment by velkymx** [comment]
![image](https://user-images.githubusercontent.com/535300/68226967-cd454100-ffa7-11e9-8092-d403c3d39a68.png)

**Comment by velkymx** [comment]
These should be in the bar to the left of the mini-map

**Comment by velkymx** [comment]
How it should work:

By default sidebars are expanded.
Upon click on the icon, the inspector should collapse completely, the tools should just show icons.
Icons are draggable onto the canvas and should have a tooltip with the title onmouseover
Inspector does not show unless the sidebars are unhidden

**Comment by tuantruong625** [comment]
@velkymx How should the `filter search` behave when the tools panel is just showing the icons? Should the filter search be hidden?

**Comment by velkymx** [comment]
Yes. Hide it
