### ISSUE TITLE
Attribute ''configuration'' is not allowed

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#790]
In the latest PM4 build available in develop, trying to save any process will throw the yellow exclamation triangle, regardless of how simple or complex it may be. Warning panel in the modeler shows The attribute ''configuration'' is not allowed.

https://www.dropbox.com/s/pu6gurjqxr5c4le/corrupted-process.mp4?dl=0

**Comment by lisa-fehr** [comment]
@velkymx can you list what version of modeler is in the latest build?

Based on the video, it doesn't have the new end events. So it is at least at **0.17.2**. We are up to **0.17.5** and may have fixed this bug in our current sprint which hasn't been versioned yet.

**Comment by lisa-fehr** [comment]
Closing. Feel free to reopen if still an issue.

**Comment by PMQABen** [comment]
https://staging-pm4qa.processmaker.net/modeler/3

Verified with ops that this server is on the latest everything, which includes
`"@processmaker/modeler": "^0.17.5",`

Re-opening ticket.

**Comment by lisa-fehr** [comment]
@PMQABen Can the issue be clarified? Are the reproduction steps still correct? I can not reproduce the bug when restoring my local environment to the versions listed on staging for screen builder (v0.20.6), vue form elements (v0.12.3) and modeler (v0.17.5).


I made a new process like the one in https://staging-pm4qa.processmaker.net/modeler/3

Here: https://staging-pm4qa.processmaker.net/modeler/8

It saved and does not display the same error. I also noticed another example of the same diagram that is error free: https://staging-pm4qa.processmaker.net/modeler/4

Any more information would help.

**Comment by velkymx** [comment]
**Description**
1. Create any Process and save
1. Go back to the main Process page
1. Note the yellow warning icon next to the Process name
1. Open the Process

**Result:**
Warning panel opens with the following message:

```
Schema Validation
//www.omg.org/spec/BPMN/20100524/MODEL}startEvent', attribute 'configuration'false The attribute 'configuration' is not allowed.
```

**Comment by velkymx** [comment]
Cannot reproduce with newest version of modeler.
