### ISSUE TITLE
Merge Warning and Error Panel

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#792]
Merge the content of the two panels into a single one. Use the Chrome console as reference.

**Comment by chipit24** [comment]
The Chrome console looks like this:
<img width="642" alt="Screen Shot 2019-11-11 at 1 53 29 PM" src="https://user-images.githubusercontent.com/7561061/68612522-b496c880-048a-11ea-893f-0e47e04e986c.png">

Let's clarify how this should be implemented during standup tomorrow.

**Comment by chipit24** [comment]
Related issue: https://github.com/ProcessMaker/modeler/issues/595

**Comment by chipit24** [comment]
On hold; waiting for mockup.

**Comment by velkymx** [comment]
![image](https://user-images.githubusercontent.com/535300/68797786-0c0f7280-060a-11ea-8bc1-b574c9b3b993.png)

![image](https://user-images.githubusercontent.com/535300/68797857-25b0ba00-060a-11ea-9623-bd2a20ea8830.png)

Button HTML:

```
        <button type="button" class="btn btn-light">
          BPMN Issues
          <span class="badge badge-primary badge-pill">4</span>
          <i class="fas fa-chevron-up"></i>
        </button>
```

**Comment by velkymx** [comment]
If there are no issues show this instead:

![image](https://user-images.githubusercontent.com/535300/68797984-6c9eaf80-060a-11ea-9c64-0bf042013bc3.png)

```
        <button type="button" class="btn btn-light">
          BPMN Issues
          <span class="badge badge-success badge-pill">0</span>          
        </button>
```
