### ISSUE TITLE
Translations Missing

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#821]
The controls are missing translations.

Boundary Event events
Gateways
Tasks is all caps for spanish.

Review and confirm all text is translated

**Comment by chipit24** [comment]
@sanjacornelius has any progress been made on this?

**Comment by chipit24** [comment]
I dragged all boundary events, all task types, and all gateways into a test process and did not see any warning about missing translations related to the bug description. Closing issue.
