### ISSUE TITLE
Pool Lanes can hide content

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#824]
Create/edit a process, add multiple controls

Add a pool control

Add at least one extra pool lane

Change the height of one of the pool lanes

Result:

Controls get hidden by the movement of additional pool lanes, can no longer be selected while hidden.

https://www.dropbox.com/s/i88kj81t1npf26q/pools-lanes-overlapping.mp4?dl=0

**Comment by chipit24** [comment]
It seems the order of adding elements and the lanes matters. When elements are added after lanes, there is no overlap issue. When elements are added before lanes, the lanes overlap the elements.

Here is a simple list of steps to reproduce this on the latest `develop` branch in standalone modeler:

1. Drag a pool onto the grid.
2. Add a lane (above or below, doesn't matter).
    * Move the start event slightly down if lane was added to the bottom, otherwise you won't be able to resize the lane to capture the element.
4. Resize the lane so it covers the start event.
