### ISSUE TITLE
Connector Elements Crown Broken

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#852]
If you load a package with a connector - the crown does not work (See slack or email connectors)

https://github.com/ProcessMaker/connector-send-email

**Comment by velkymx** [comment]
Clicking on a typical element:

![image](https://user-images.githubusercontent.com/535300/69583691-5096f880-0f90-11ea-9703-1c12e67985c8.png)

Clicking on a connector:

![image](https://user-images.githubusercontent.com/535300/69583715-61e00500-0f90-11ea-9651-bb3e1390b941.png)

**Comment by lisa-fehr** [comment]
The send email connector is easy. But I'm not sure how the other connectors are written. We will need to debate options.

Any connector that extends task, needs to remove the template at the top of its component.

```
<template>
  <div>
  </div>
</template>
```
![connector-send-email](https://user-images.githubusercontent.com/6653340/69646467-dd47c200-1035-11ea-8998-63bf8791d87b.png)
