### ISSUE TITLE
Change order of components in the controls panel

### ISSUE THREAD

**Issue by chipit24** [ProcessMaker/modeler#895]
<img width="256" alt="Screen Shot 2019-12-05 at 11 43 04 AM" src="https://user-images.githubusercontent.com/7561061/70255223-69ec3180-1754-11ea-8345-2194234a1620.png">

Modify the order of the elements so that the "grouped" elements (those with the new element select dropdown) are at the top. The order should be (from top to bottom):
 * Start Event
 * Intermediate Event
 * End Event
 * Task
 * Gateway
 * All other components ...

**Comment by chipit24** [comment]
This can be done once https://github.com/ProcessMaker/modeler/issues/893 and https://github.com/ProcessMaker/modeler/issues/892 are complete.

**Comment by tuantruong625** [comment]
Adding a border for the last control can be part of this issue.

<img width="263" alt="Screen Shot 2019-12-05 at 2 47 20 PM" src="https://user-images.githubusercontent.com/26545455/70268299-26062600-176e-11ea-8e5d-0da161230afd.png">
