### ISSUE TITLE
Remove animation from validation icon chevron

### ISSUE THREAD

**Issue by JCook21** [ProcessMaker/modeler#914]
# Bug report issue
## Description

The chevrons on the inspectors' headers do not animate when expanding/collapsing. 

<img width="252" alt="Screen Shot 2020-01-03 at 1 40 25 PM" src="https://user-images.githubusercontent.com/26545455/71742091-9b791b00-2e2e-11ea-8290-dac0a1ec02a8.png">
Related to #909. Add transitions to the panels in the inspector config.

**Comment by chipit24** [comment]
@velkymx This change will be required in vue-form-elements and will have the side-effect of also having the animations show up in screen-builder, not just in modeler. Is this ok?

**Comment by JCook21** [comment]
We discussed this with @velkymx and the decision was to remove the animation from the Chevron.
