### ISSUE TITLE
Add test for boundary event positioning and validation

### ISSUE THREAD

**Issue by chipit24** [ProcessMaker/modeler#934]
Add tests to support the work done in https://github.com/ProcessMaker/modeler/pull/932. The tests should verify the following:

 * The validation correctly works when adding boundary events from the crown dropdown menu (the button to add the boundary event should be disabled if it's invalid).
   * All buttons should be disabled when all 12 ports are occupied by a boundary event.
   * The error boundary event button should  be disabled when there is already a boundary event on the target.
 * Clicking to add a boundary event should fill an empty port and not overlap a boundary event already on the target.

**Comment by lisa-fehr** [comment]
**As a note:** You can have more than 12 boundary events if you overlap boundary events manually and leave ports open. This is probably ok if the user wants to do this.
