### ISSUE TITLE
Boundary event / Lane console error

### ISSUE THREAD

**Issue by tuantruong625** [ProcessMaker/modeler#936]
# Bug report issue
## Description
When I add a lane to a pool with a boundary event a console error is thrown.
## Reproduction steps
- Drag task
- Add any boundary event to task
- Drag pool onto paper
- Add lane
## Expected behaviour
- no console errors are thrown
## Actual behaviour
- console error is thrown
## Software used
- Modeler, `912-add-boundary-dropdown` branch
- Chrome 78
- MacOS Catalina

## Other information

**Console Error**

```
[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'component' of null"

found in

---> <CrownConfig> at src/components/poolLaneCrownConfig.vue
       <ProcessmakerModelerLane> at src/components/nodes/poolLane/poolLane.vue
         <Modeler> at src/components/Modeler.vue
           <ModelerApp> at src/ModelerApp.vue
             <Root>
```

**Comment by chipit24** [comment]
This appears to be the same issue that was fixed a couple days ago: https://github.com/ProcessMaker/modeler/issues/908.

**Comment by tuantruong625** [comment]
Fixed by merging latest changes from develop.
