### ISSUE TITLE
Make disabled icons non-transparent

### ISSUE THREAD

**Issue by JCook21** [ProcessMaker/modeler#939]
Currently disabled icons in modeler are semi-transparent. This is causing the issue shown in the screenshot below where the elements underneath are showing through. This is potentially confusing and should be changed so that disabled icons are fully opaque.

<img width="352" alt="Screen Shot 2019-12-11 at 11 08 15 AM" src="https://user-images.githubusercontent.com/858371/70638390-cb097e80-1c06-11ea-861d-769a13d092a7.png">

**Comment by chipit24** [comment]
No longer an issue as the toolbar will be placed above the modeler with the breadcrumbs.
