### ISSUE TITLE
Start Timer Event Error when selecting end date. 

### ISSUE THREAD

**Issue by sanjacornelius** [ProcessMaker/modeler#960]
# Bug report issue
## Description
When configuring an end date for the Start Timer Event using the date-picker the following error is displayed:
```
The undefined is not a valid date with format MM/DD/YYYY
```
After a few clicks off and on the control the error disappears.

## Reproduction steps
1. Drag a start event onto the paper and select the Start Timer Event.
2. Configure the Timing Controls.
3. Select the 'On' option for the 'End' configurations and select a date from the date-picker.
## Expected behaviour
No error displays
## Actual behaviour
The error ``` The undefined is not a valid date with format MM/DD/YYYY``` is displayed.
## Other information
https://www.loom.com/share/470ad6224375433586b23d06b9d383e6

**Comment by JCook21** [comment]
I can reproduce this on the latest build of modeler. I'll look into this.
