### ISSUE TITLE
Nudging Elements with Arrow Keys

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#966]
I want to be able to use the arrow keys on my keyboard to move elements on the canvas.

**Comment by chipit24** [comment]
Question: @velkymx should the label remain visible when moving with the arrow keys?

Currently, when clicking and dragging an element, we hide the element's label. If we try to keep this behaviour consistent when moving with the arrow keys, it may result in the label flashing as the user nudges the shape around.

**Comment by chipit24** [comment]
**Acceptance criteria:**
 * When an element is highlighted, pressed the arrow keys should move the shape in the appropriate direction.
   * The amount the shape is moved by will be 1/2 the grid size (the grid size is currently 10 px so the shape should move in 5 px amounts).
 * The label remains visible when moving the shape with the arrow keys.
 * Moving with the arrow keys should not be allowed for pool lanes, boundary events, and flow elements (message flows, sequence flows, and association flows).
   * One caveat is that it's possible to move flow _vertices_ with the arrow keys.
* Moving a shape with the arrow keys should update the position properties for the underlying BPMN element.
* Moving a shape with the arrow keys should save the new position to the undo/redo stack.
* Moving a shape with the arrow keys inside a pool should:
   * Expand the pool to contain the shape if the element reaches the pool's edge.
   * Add the shape to the new pool lane if the shape was nudged over into a new lane.
