### ISSUE TITLE
Expression Requiring Quotes

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#99]
When I put an expression in a gateway evaluation. I must quote the expression for it to work. 

This works: "color==blue"

This does not: color==blue

**Comment by tdondich** [comment]
Is it possible to have color == "blue"

?  To identify that blue is a string?  I'm trying to reduce the amount of different syntaxes a process designer must know.

**Comment by josemaldonad0** [comment]
In my tests I found that what works more consistently is that last version, color=="blue"

**Comment by caleeli** [comment]
To work, in the expression the value "blue" should enclosed in double quotes

**Comment by tdondich** [comment]
@caleeli Is this documented somewhere?  What syntax engine are you using?  We need to doc this for documentation sake.
