### ISSUE TITLE
Add missing animation to inspector panel

### ISSUE THREAD

**Issue by tuantruong625** [ProcessMaker/modeler#994]
# Bug report issue
## Description

The chevrons on the inspectors' headers do not animate when expanding/collapsing. 

<img width="252" alt="Screen Shot 2020-01-03 at 1 40 25 PM" src="https://user-images.githubusercontent.com/26545455/71742091-9b791b00-2e2e-11ea-8290-dac0a1ec02a8.png">

**Comment by JCook21** [comment]
I think this duplicates #914. @tuantruong625 can you look at merging these issues?

**Comment by tuantruong625** [comment]
Duplicate Issue #914
