### ISSUE TITLE
Change Task Warning

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#997]
After placing a configured task, and then trying to change it to another type of task, show a warning:

"Changing this task type will replace your current configuration"

[Cancel] [Confirm]

**Comment by chipit24** [comment]
Acceptance criteria:
 * A confirmation modal should open when the user attempts to change the element type:
   * This modal should only be displayed after the element select dropdown has been closed at least once.
   * Clicking confirm should switch to the new element, and clicking cancel should close the modal and retain the same element.
