### ISSUE TITLE
Help Links Broken

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#998]
Links in Process Modeler accordions do not work because of a symbol replacement in the link. The real links use a hashtag symbol (#), but the application links use %23 in its place. If I copy the link from the application and change %23 to #, then the link works.

When these question marks rolled out in an earlier staged build, I spot-tested a couple of them and then worked. I think they broke in Beta 11 R2. I suspect that there may be something in the build that doesn't like the hashtag symbol and replaces it with a Unicode representation, much like spaces in URLs are represented by %20 in a URL. I don't know if at some point something converted the hashtag internally.

We will need to add this link testing to final QA tests. I will also help test them when I hear this has been addressed.

**Comment by chipit24** [comment]
Looks like `%23` is hard-coded in the URL and can be updated in modeler: https://github.com/ProcessMaker/modeler/blob/b7f2097cf5b184c217950ced8f07106350948c4d/src/components/inspectors/InspectorPanel.vue#L92.

This issue shows up for question mark link in the inspector panel for sequence flows coming from exclusive and inclusive gateways.

<img width="638" alt="Screen Shot 2020-01-06 at 3 05 03 PM" src="https://user-images.githubusercontent.com/7561061/71845266-ef396d80-3095-11ea-8559-5f585030859e.png">
